#!/bin/bash
# Setup script for Neon + GitHub Actions integration

echo "=========================================="
echo "Neon + GitHub Actions Setup Guide"
echo "=========================================="
echo ""

echo "Step 1: Get Neon API Key"
echo "------------------------"
echo "1. Go to: https://console.neon.tech/"
echo "2. Sign in to your account"
echo "3. Click on your profile (top right)"
echo "4. Go to 'Developer Settings' or 'API Keys'"
echo "5. Click 'Create API Key'"
echo "6. Give it a name: 'GitHub Actions'"
echo "7. Copy the API key (starts with 'neon_')"
echo ""
read -p "Press Enter when you have your API key..."

echo ""
echo "Step 2: Get Neon Project ID"
echo "---------------------------"
echo "1. In Neon Console, select your project"
echo "2. Go to 'Settings' → 'General'"
echo "3. Find 'Project ID' (looks like: ep-xxxxx-xxxxx)"
echo "4. Copy the Project ID"
echo ""
read -p "Press Enter when you have your Project ID..."

echo ""
echo "Step 3: Add to GitHub"
echo "---------------------"
echo "1. Go to your GitHub repository"
echo "2. Click 'Settings' → 'Secrets and variables' → 'Actions'"
echo ""
echo "Add Secret:"
echo "  Name: NEON_API_KEY"
echo "  Value: [paste your API key]"
echo ""
echo "Add Variable:"
echo "  Name: NEON_PROJECT_ID"
echo "  Value: [paste your Project ID]"
echo ""
read -p "Press Enter when you've added both to GitHub..."

echo ""
echo "✅ Setup complete!"
echo ""
echo "Next steps:"
echo "1. Commit the workflow files"
echo "2. Push to GitHub"
echo "3. Create a test PR to verify it works"
echo ""

