import React, { createContext, useContext, useState, ReactNode, useEffect, useCallback, useMemo } from 'react';

// Define the available languages
export type Language = 'en' | 'tr';

// Create the translations object for both languages
const translations = {
  en: {
    // Common
    appName: 'EduLearn Platform',
    loading: 'Loading...',
    save: 'Save',
    cancel: 'Cancel',
    edit: 'Edit',
    delete: 'Delete',
    confirm: 'Confirm',
    back: 'Back',
    next: 'Next',
    previous: 'Previous',
    search: 'Search',
    filter: 'Filter',
    sort: 'Sort',
    refresh: 'Refresh',
    
    // Navigation
    dashboard: 'Dashboard',
    courses: 'Courses',
    assignments: 'Assignments',
    calendar: 'Calendar',
    resources: 'Resources',
    achievements: 'Achievements',
    profile: 'Profile',
    adminPanel: 'Admin Panel',
    courseGenerator: 'AI Course Generator',
    learningTrails: 'Learning Trails',
    smartSuggestions: 'Smart Suggestions',
    advancedAILearning: 'Advanced AI Learning',
    entranceExams: 'Entrance Exams',
    learningPaths: 'Learning Paths',
    integrations: 'Integrations',
    googleDrive: 'Google Drive',
    googleMeet: 'Google Meet',
    googleCalendar: 'Google Calendar',
    
    // Auth
    login: 'Login',
    register: 'Register',
    username: 'Username',
    password: 'Password',
    confirmPassword: 'Confirm Password',
    displayName: 'Display Name',
    forgotPassword: 'Forgot Password?',
    noAccount: 'Don\'t have an account?',
    haveAccount: 'Already have an account?',
    loginNow: 'Login Now',
    registerNow: 'Register Now',
    logout: 'Logout',
    
    // Dashboard
    welcomeBack: 'Welcome back',
    yourProgress: 'Your Progress',
    enrolledCourses: 'Enrolled Courses',
    upcomingAssignments: 'Upcoming Assignments',
    viewAll: 'View All',
    enrolledIn: 'Enrolled in',
    course: 'Course',
    coursesPlural: 'Courses',
    continueLeaning: 'Continue Learning',
    completed: 'Completed',
    dueDate: 'Due Date',
    continueWhereverYouLeftOff: 'Continue learning where you left off',
    searchCoursesResources: 'Search courses, resources...',
    dailyChallenge: 'Daily Challenge',
    coursesInProgress: 'Courses in Progress',
    completedCourses: 'Completed Courses',
    pendingAssignments: 'Pending Assignments',
    continueText: 'Continue learning! Click to see all your courses or find new ones.',
    greatJob: 'Great job! Review completed courses or explore advanced topics.',
    timeToSubmit: 'Time to submit! Click to complete your assignments.',
    allCaughtUp: 'All caught up! Check for new assignments.',
    checkForNewAssignments: 'Check for new assignments.',
    amazingProgress: 'Amazing progress! View all achievements and unlock more.',
    startEarningAchievements: 'Start earning achievements by completing challenges!',
    yourAchievements: 'Your Achievements',
    levelUpYourLearning: 'Level up your learning journey',
    share: 'Share',
    yourLevel: 'Your Level',
    progressToLevel: 'Progress to Level',
    completeChallengesToUnlock: 'Complete challenges to unlock your level!',
    activeChallenges: 'Active Challenges',
    noActiveChallenges: 'No active challenges',
    startChallenge: 'Start Challenge',
    recentAchievements: 'Recent Achievements',
    noAchievementsYet: 'No achievements yet',
    completeCoursesAndChallenges: 'Complete courses and challenges to earn achievements!',
    viewChallenges: 'View Challenges',
    leaderboards: 'Leaderboards',
    quickChallenge: 'Quick Challenge',
    pickUpWhereYouLeftOff: 'Pick up where you left off - your courses are waiting for you below, or explore new ones!',
    noCourseInProgress: 'No courses in progress',
    readyToStartLearning: 'Ready to start learning? Browse our course catalog and enroll in something that interests you!',
    exploreCourses: 'Explore Courses',
    getAIRecommendations: 'Get AI Recommendations',
    recommendedForYou: 'Recommended For You',
    aiPoweredSuggestions: 'AI-powered course suggestions based on your interests and learning progress - perfect next steps for your journey!',
    perfectNextSteps: 'perfect next steps for your journey!',
    
    // Courses
    allCourses: 'All Courses',
    availableCourses: 'Available Courses',
    enrolled: 'Enrolled',
    myCourses: 'My Courses',
    inProgress: 'In Progress',
    enrollNow: 'Enroll Now',
    continueButton: 'Continue',
    noCourses: 'No courses available',
    courseDuration: 'Duration',
    courseModules: 'Modules',
    hours: 'hours',
    searchPlaceholder: 'Search courses...',
    enrollmentSuccessful: 'Enrollment Successful',
    enrollmentFailed: 'Enrollment Failed',
    enrollmentSuccessDescription: 'You have been enrolled in the course',
    enrollmentFailedDescription: 'Failed to enroll in the course',
    manageLearningJourney: 'Manage your learning journey',
    noCoursesFound: 'No courses found',
    noCoursesFoundDescription: 'You haven\'t enrolled in any courses yet. Explore available courses to start your learning journey.',
    noCourseMatches: 'No courses match your search criteria.',
    noAvailableCourses: 'No courses available at the moment.',
    checkBackLater: 'Check back later for new courses.',
    tryDifferentSearch: 'Try a different search query.',
    module: 'Module',
    complete: 'Complete',
    aiPersonalization: 'AI Personalization',
    personalizedForYou: 'Personalized for You',
    learningObjectives: 'Learning Objectives',
    aiAdaptedContent: 'AI-Adapted Content',
    selectLessonForContent: 'Select a lesson to see AI-personalized content',
    personalizedContentAvailable: 'Personalized content available',
    
    // Course Generator
    generateCourse: 'Generate Course',
    courseTitle: 'Course Title',
    courseDescription: 'Course Description',
    courseCategory: 'Category',
    topicInput: 'Topic',
    generateCourseButton: 'Generate Course',
    courseGenerated: 'Course Generated Successfully',
    saveCourse: 'Save Course',
    
    // Course Detail
    courseOverview: 'Course Overview',
    moduleOverview: 'Module Overview',
    lessonContent: 'Lesson Content',
    prerequisites: 'Prerequisites',
    learningOutcomes: 'Learning Outcomes',
    difficultyLevel: 'Difficulty Level',
    estimatedDuration: 'Estimated Duration',
    completionRate: 'Completion Rate',
    
    // Lesson Page
    lessonNotFound: 'Lesson Not Found',
    lessonNotFoundDescription: 'The lesson you are looking for does not exist or has not been created yet.',
    backToCourse: 'Back to Course',
    personalizedIntro: 'AI Personalized Introduction',
    practiceExercises: 'Practice Exercises',
    nextSteps: 'Next Steps',
    completeLesson: 'Complete Lesson',
    nextLesson: 'Next Lesson',
    previousLesson: 'Previous Lesson',
    minutes: 'minutes',
    levelInput: 'Level',
    targetAudienceInput: 'Target Audience',
    specificFocusInput: 'Specific Focus',
    generatingCourse: 'Generating Course...',
    generateButton: 'Generate',
    
    // Assignments
    assignmentsDue: 'Assignments Due',
    noAssignments: 'No assignments due',
    submitAssignment: 'Submit Assignment',
    viewDetails: 'View Details',
    
    // Calendar
    monthlyView: 'Monthly View',
    upcoming: 'Upcoming',
    noEvents: 'No events on this date',
    hasAssignments: 'assignments due',
    selectDate: 'Select a date',
    
    // Admin
    adminDashboard: 'Admin Dashboard',
    manageUsers: 'Manage Users',
    manageCourses: 'Manage Courses',
    addTurkishCourses: 'Add Turkish University Entrance Exam Courses',
    
    // Turkish Exam Courses
    turkishCoursesAdded: 'Turkish university entrance exam courses added successfully',
    tyt: 'TYT',
    ayt: 'AYT',
    ydt: 'YDT',
    
    // Resources
    allResources: 'All Resources',
    documents: 'Documents',
    media: 'Media',
    links: 'Links',
    uploadResource: 'Upload Resource',
    downloadResource: 'Download',
    openLink: 'Open Link',
    searchResources: 'Search resources...',
    filterByCourse: 'Filter by Course',

    // AI Features
    aiPoweredModules: 'AI-Powered Learning Modules',
    personalizedContent: 'Personalized Content',
    aiLearningAssistant: 'AI Learning Assistant',
    recommendedPractice: 'Recommended Practice',
    nextRecommendedSteps: 'Next recommended steps',
    startLearning: 'Start Learning',
    refreshContent: 'Refresh Content',
    noAiModulesAvailable: 'No AI Modules Available',
    
    // Entrance Exams
    entranceExamPrep: 'Entrance Exam Preparation',
    myLearningPaths: 'My Learning Paths',
    exploreExams: 'Explore Exams',
    createNewPath: 'Create New Path',
    createAiPoweredPath: 'Create AI-Powered Learning Path',
    learningPath: 'Learning Path',
    aiPersonalized: 'AI-Personalized',
    moduleTree: 'Module Tree',
    aiEnhanced: 'AI Enhanced',
    examType: 'Exam Type',
    specificExam: 'Specific Exam',
    currentLevel: 'Current Level',
    learningStyle: 'Learning Style',
    weeklyStudyHours: 'Weekly Study Hours',
    targetScore: 'Target Score',
    examDate: 'Exam Date',
    strengths: 'Strengths',
    areasForImprovement: 'Areas for Improvement',
    specialRequirements: 'Special Requirements',
    generateLearningPath: 'Generate Learning Path',
    continueLearning: 'Continue Learning',
    
    // Course Detail
    courseNotFound: 'Course not found',
    courseNotFoundDescription: 'The course you\'re looking for doesn\'t exist.',
    
    // Adaptive Learning Path Visualization
    pathNotFound: 'Learning Path Not Found',
    pathNotFoundDescription: 'The learning path you\'re looking for doesn\'t exist.',
    overallProgress: 'Overall Progress',
    learningPathSteps: 'Learning Path Steps',
    difficultyMatch: 'Difficulty Match',
    timeEstimate: 'Time Estimate',
    prerequisitesCompleted: 'Prerequisites Completed',
    prerequisitesIncomplete: 'Prerequisites Incomplete',
    markComplete: 'Mark Complete',
    learningAnalytics: 'Learning Analytics',
    timeSpent: 'Time Spent',
    averageScore: 'Average Score',
    learningVelocity: 'Learning Velocity',
    strongAreas: 'Strong Areas',
    improvementAreas: 'Areas for Improvement',
    recommendedNextCourse: 'Recommended Next Course',
    confidence: 'Confidence',
    startCourse: 'Start Course',
    identifiedSkillGaps: 'Identified Skill Gaps',
    optimizedPathSuggestions: 'Optimized Path Suggestions',
    refreshRecommendations: 'Refresh Recommendations',
    addToPath: 'Add to Path',
    priority: 'Priority',
    detectedLearningStyle: 'Detected Learning Style',
    optimalLearningPace: 'Optimal Learning Pace',
    pathView: 'Path View',
    analytics: 'Analytics',
    recommendations: 'Recommendations',
    progressUpdated: 'Progress Updated',
    learningPathProgressSaved: 'Learning path progress has been saved',
    recommendationsUpdated: 'Recommendations Updated',
    adaptiveRecommendationsGenerated: 'New adaptive recommendations have been generated',
    successRate: 'Success Rate',
    start: 'Start',
    steps: 'Steps',
    pace: 'Pace',
    
    // Adaptive Learning Demo
    adaptiveLearningPathVisualization: 'Adaptive Learning Path Visualization',
    adaptiveLearningDescription: 'Experience personalized learning paths powered by AI that adapt to your progress, learning style, and goals.',
    aiPoweredRecommendations: 'AI-Powered Recommendations',
    personalizedLearningPaths: 'Personalized Learning Paths',
    progressTracking: 'Progress Tracking',
    adaptiveInsights: 'Adaptive Insights',
    selectLearningPath: 'Select Learning Path',
    adaptivePathVisualization: 'Adaptive Path Visualization',
    pathId: 'Path ID',
    howItWorks: 'How It Works',
    adaptiveFeatures: 'Adaptive Features',
    analyticsFeatures: 'Analytics Features',
    personalizedContentRecommendations: 'Personalized content recommendations',
    dynamicDifficultyAdjustment: 'Dynamic difficulty adjustment',
    learningStyleDetection: 'Learning style detection',
    prerequisiteTracking: 'Prerequisite tracking',
    successProbabilityCalculation: 'Success probability calculation',
    timeSpentTracking: 'Time spent tracking',
    performanceAnalytics: 'Performance analytics',
    learningVelocityMeasurement: 'Learning velocity measurement',
    skillGapIdentification: 'Skill gap identification',
    improvementRecommendations: 'Improvement recommendations',
    authenticationRequired: 'Authentication Required',
    pleaseLoginToViewAdaptivePaths: 'Please login to view adaptive learning paths',
    
    // Advanced Adaptive Learning
    visualLearning: 'Visual Learning',
    auditoryLearning: 'Auditory Learning',
    kinestheticLearning: 'Kinesthetic Learning',
    readingWritingLearning: 'Reading/Writing Learning',
    difficultyAdjustment: 'Difficulty Adjustment',
    currentDifficulty: 'Current Difficulty',
    recommendedDifficulty: 'Recommended Difficulty',
    increaseDifficulty: 'Increase Difficulty',
    decreaseDifficulty: 'Decrease Difficulty',
    maintainDifficulty: 'Maintain Current Difficulty',
    applyAdjustment: 'Apply Adjustment',
    predictiveAnalytics: 'Predictive Analytics',
    estimatedTimeToCompletion: 'Estimated Time to Completion',
    riskLevel: 'Risk Level',
    strugglingAreas: 'Struggling Areas',
    strengthAreas: 'Strength Areas',
    recommendedInterventions: 'Recommended Interventions',
    easy: 'Easy',
    medium: 'Medium',
    hard: 'Hard',
    low: 'Low',
    high: 'High',
    normal: 'Normal',
    days: 'days',
    actionable: 'Actionable',
    strength: 'Strength',
    weakness: 'Weakness',
    opportunity: 'Opportunity',
    risk: 'Risk',
    noInsightsAvailable: 'No insights available yet',
    insightsWillAppearAsYouProgress: 'Insights will appear as you progress through your learning journey'
  },
  tr: {
    // Common
    appName: 'EduLearn Platformu',
    loading: 'Yükleniyor...',
    save: 'Kaydet',
    cancel: 'İptal',
    edit: 'Düzenle',
    delete: 'Sil',
    confirm: 'Onayla',
    back: 'Geri',
    next: 'İleri',
    previous: 'Önceki',
    search: 'Ara',
    filter: 'Filtrele',
    sort: 'Sırala',
    refresh: 'Yenile',
    
    // Navigation
    dashboard: 'Gösterge Paneli',
    courses: 'Kurslar',
    assignments: 'Ödevler',
    calendar: 'Takvim',
    resources: 'Kaynaklar',
    achievements: 'Başarılar',
    profile: 'Profil',
    adminPanel: 'Admin Paneli',
    courseGenerator: 'Yapay Zeka Kurs Oluşturucu',
    learningTrails: 'Öğrenme Parkurları',
    smartSuggestions: 'Akıllı Öneriler',
    advancedAILearning: 'Gelişmiş AI Öğrenim',
    entranceExams: 'Giriş Sınavları',
    learningPaths: 'Öğrenme Yolları',
    integrations: 'Entegrasyonlar',
    googleDrive: 'Google Drive',
    googleMeet: 'Google Meet',
    googleCalendar: 'Google Takvim',
    
    // Auth
    login: 'Giriş Yap',
    register: 'Kayıt Ol',
    username: 'Kullanıcı Adı',
    password: 'Şifre',
    confirmPassword: 'Şifreyi Onayla',
    displayName: 'Görünen Ad',
    forgotPassword: 'Şifreni mi unuttun?',
    noAccount: 'Hesabınız yok mu?',
    haveAccount: 'Zaten hesabınız var mı?',
    loginNow: 'Şimdi Giriş Yap',
    registerNow: 'Şimdi Kayıt Ol',
    logout: 'Çıkış Yap',
    
    // Dashboard
    welcomeBack: 'Tekrar hoş geldiniz',
    yourProgress: 'İlerlemeniz',
    enrolledCourses: 'Kayıtlı Kurslar',
    upcomingAssignments: 'Yaklaşan Ödevler',
    viewAll: 'Tümünü Görüntüle',
    enrolledIn: 'Kayıtlı',
    course: 'Kurs',
    coursesPlural: 'Kurslar',
    continueLeaning: 'Öğrenmeye Devam Et',
    completed: 'Tamamlandı',
    dueDate: 'Bitiş Tarihi',
    continueWhereverYouLeftOff: 'Kaldığınız yerden öğrenmeye devam edin',
    searchCoursesResources: 'Kurs, kaynak ara...',
    dailyChallenge: 'Günlük Meydan Okuma',
    coursesInProgress: 'Devam Eden Kurslar',
    completedCourses: 'Tamamlanan Kurslar',
    pendingAssignments: 'Bekleyen Ödevler',
    continueText: 'Öğrenmeye devam et! Tüm kurslarını görmek veya yenilerini bulmak için tıkla.',
    greatJob: 'Harika iş! Tamamlanan kursları incele veya ileri konuları keşfet.',
    timeToSubmit: 'Teslim zamanı! Ödevlerini tamamlamak için tıkla.',
    allCaughtUp: 'Hepsi tamam! Yeni ödevleri kontrol et.',
    checkForNewAssignments: 'Yeni ödevleri kontrol et.',
    amazingProgress: 'İnanılmaz ilerleme! Tüm başarıları görüntüle ve daha fazlasını aç.',
    startEarningAchievements: 'Meydan okumaları tamamlayarak başarı kazanmaya başla!',
    yourAchievements: 'Başarıların',
    levelUpYourLearning: 'Öğrenme yolculuğunu seviye atla',
    share: 'Paylaş',
    yourLevel: 'Seviyeniz',
    progressToLevel: 'Seviye İlerlemesi',
    completeChallengesToUnlock: 'Seviyenizi açmak için meydan okumaları tamamlayın!',
    activeChallenges: 'Aktif Meydan Okumalar',
    noActiveChallenges: 'Aktif meydan okuma yok',
    startChallenge: 'Meydan Okuma Başlat',
    recentAchievements: 'Son Başarılar',
    noAchievementsYet: 'Henüz başarı yok',
    completeCoursesAndChallenges: 'Başarı kazanmak için kursları ve meydan okumaları tamamla!',
    viewChallenges: 'Meydan Okumaları Görüntüle',
    leaderboards: 'Sıralama Tabloları',
    quickChallenge: 'Hızlı Meydan Okuma',
    pickUpWhereYouLeftOff: 'Kaldığın yerden devam et - kursların seni aşağıda bekliyor, veya yenilerini keşfet!',
    noCourseInProgress: 'Devam eden kurs yok',
    readyToStartLearning: 'Öğrenmeye başlamaya hazır mısın? Kurs kataloğumuzu gözden geçir ve ilgini çeken bir kursa kaydol!',
    exploreCourses: 'Kursları Keşfet',
    getAIRecommendations: 'AI Önerileri Al',
    recommendedForYou: 'Sizin İçin Önerilen',
    aiPoweredSuggestions: 'İlgi alanların ve öğrenme ilerlemen temelinde yapay zeka destekli kurs önerileri - yolculuğun için mükemmel sonraki adımlar!',
    perfectNextSteps: 'yolculuğun için mükemmel sonraki adımlar!',
    
    // Courses
    allCourses: 'Tüm Kurslar',
    availableCourses: 'Mevcut Kurslar',
    enrolled: 'Kayıtlı',
    myCourses: 'Kurslarım',
    inProgress: 'Devam Eden',
    enrollNow: 'Şimdi Kaydol',
    continueButton: 'Devam Et',
    noCourses: 'Mevcut kurs yok',
    courseDuration: 'Süre',
    courseModules: 'Modüller',
    hours: 'saat',
    searchPlaceholder: 'Kurs ara...',
    enrollmentSuccessful: 'Kayıt Başarılı',
    enrollmentFailed: 'Kayıt Başarısız',
    enrollmentSuccessDescription: 'Kursa başarıyla kaydoldunuz',
    enrollmentFailedDescription: 'Kursa kaydolma işlemi başarısız oldu',
    manageLearningJourney: 'Öğrenme yolculuğunuzu yönetin',
    noCoursesFound: 'Kurs bulunamadı',
    noCoursesFoundDescription: 'Henüz herhangi bir kursa kaydolmadınız. Öğrenme yolculuğunuzu başlatmak için mevcut kursları keşfedin.',
    noCourseMatches: 'Arama kriterlerinizle eşleşen kurs bulunamadı.',
    noAvailableCourses: 'Şu anda mevcut kurs yok.',
    checkBackLater: 'Yeni kurslar için daha sonra tekrar kontrol edin.',
    tryDifferentSearch: 'Farklı bir arama terimi deneyin.',
    module: 'Modül',
    complete: 'Tamamlandı',
    aiPersonalization: 'AI Kişiselleştirme',
    personalizedForYou: 'Sizin İçin Kişiselleştirildi',
    learningObjectives: 'Öğrenme Hedefleri',
    aiAdaptedContent: 'AI Uyarlanmış İçerik',
    selectLessonForContent: 'AI-kişiselleştirilmiş içeriği görmek için bir ders seçin',
    personalizedContentAvailable: 'Kişiselleştirilmiş içerik mevcut',
    
    // Course Generator
    generateCourse: 'Kurs Oluştur',
    courseTitle: 'Kurs Başlığı',
    courseDescription: 'Kurs Açıklaması',
    courseCategory: 'Kategori',
    topicInput: 'Konu',
    generateCourseButton: 'Kurs Oluştur',
    courseGenerated: 'Kurs Başarıyla Oluşturuldu',
    saveCourse: 'Kursu Kaydet',
    
    // Course Detail
    courseOverview: 'Kurs Genel Bakış',
    moduleOverview: 'Modül Genel Bakış',
    lessonContent: 'Ders İçeriği',
    prerequisites: 'Ön Koşullar',
    learningOutcomes: 'Öğrenme Çıktıları',
    difficultyLevel: 'Zorluk Seviyesi',
    estimatedDuration: 'Tahmini Süre',
    completionRate: 'Tamamlanma Oranı',
    
    // Lesson Page
    lessonNotFound: 'Ders Bulunamadı',
    lessonNotFoundDescription: 'Aradığınız ders mevcut değil veya henüz oluşturulmadı.',
    backToCourse: 'Kursa Dön',
    personalizedIntro: 'AI Kişiselleştirilmiş Giriş',
    practiceExercises: 'Alıştırmalar',
    nextSteps: 'Sonraki Adımlar',
    completeLesson: 'Dersi Tamamla',
    nextLesson: 'Sonraki Ders',
    previousLesson: 'Önceki Ders',
    minutes: 'dakika',
    levelInput: 'Seviye',
    targetAudienceInput: 'Hedef Kitle',
    specificFocusInput: 'Özel Odak',
    generatingCourse: 'Kurs Oluşturuluyor...',
    generateButton: 'Oluştur',
    
    // Assignments
    assignmentsDue: 'Yaklaşan Ödevler',
    noAssignments: 'Yaklaşan ödev yok',
    submitAssignment: 'Ödevi Gönder',
    viewDetails: 'Detayları Görüntüle',
    
    // Calendar
    monthlyView: 'Aylık Görünüm',
    upcoming: 'Yaklaşan',
    noEvents: 'Bu tarihte etkinlik yok',
    hasAssignments: 'ödev var',
    selectDate: 'Bir tarih seçin',
    
    // Admin
    adminDashboard: 'Admin Gösterge Paneli',
    manageUsers: 'Kullanıcıları Yönet',
    manageCourses: 'Kursları Yönet',
    addTurkishCourses: 'YKS Kurslarını Ekle',
    
    // Turkish Exam Courses
    turkishCoursesAdded: 'YKS kursları başarıyla eklendi',
    tyt: 'TYT',
    ayt: 'AYT',
    ydt: 'YDT',
    
    // Resources
    allResources: 'Tüm Kaynaklar',
    documents: 'Dokümanlar',
    media: 'Medya',
    links: 'Bağlantılar',
    uploadResource: 'Kaynak Yükle',
    downloadResource: 'İndir',
    openLink: 'Bağlantıyı Aç',
    searchResources: 'Kaynakları ara...',
    filterByCourse: 'Kursa Göre Filtrele',

    // AI Features
    aiPoweredModules: 'Yapay Zeka Destekli Öğrenme Modülleri',
    personalizedContent: 'Kişiselleştirilmiş İçerik',
    aiLearningAssistant: 'Yapay Zeka Öğrenme Asistanı',

    recommendedPractice: 'Önerilen Pratik',
    nextRecommendedSteps: 'Önerilen sonraki adımlar',
    startLearning: 'Öğrenmeye Başla',
    refreshContent: 'İçeriği Yenile',
    noAiModulesAvailable: 'Yapay Zeka Modülü Mevcut Değil',

    
    // Entrance Exams
    entranceExamPrep: 'Üniversite Sınavı Hazırlığı',
    myLearningPaths: 'Öğrenme Yollarım',
    exploreExams: 'Sınavları Keşfet',
    createNewPath: 'Yeni Yol Oluştur',
    createAiPoweredPath: 'Yapay Zeka Destekli Öğrenme Yolu Oluştur',
    examType: 'Sınav Türü',
    specificExam: 'Belirli Sınav',
    currentLevel: 'Mevcut Seviye',
    learningStyle: 'Öğrenme Stili',
    weeklyStudyHours: 'Haftalık Çalışma Saati',
    targetScore: 'Hedef Puan',
    examDate: 'Sınav Tarihi',
    strengths: 'Güçlü Yönler',
    areasForImprovement: 'Geliştirilmesi Gereken Alanlar',
    specialRequirements: 'Özel Gereksinimler',
    generateLearningPath: 'Öğrenme Yolu Oluştur',
    continueLearning: 'Öğrenmeye Devam Et',
    
    // Adaptive Learning Path Visualization
    pathNotFound: 'Öğrenme Yolu Bulunamadı',
    pathNotFoundDescription: 'Aradığınız öğrenme yolu mevcut değil.',
    overallProgress: 'Genel İlerleme',
    learningPathSteps: 'Öğrenme Yolu Adımları',
    difficultyMatch: 'Zorluk Eşleşmesi',
    timeEstimate: 'Süre Tahmini',
    prerequisitesCompleted: 'Ön Koşullar Tamamlandı',
    prerequisitesIncomplete: 'Ön Koşullar Eksik',
    markComplete: 'Tamamlandı Olarak İşaretle',
    learningAnalytics: 'Öğrenme Analitikleri',
    timeSpent: 'Harcanan Süre',
    averageScore: 'Ortalama Puan',
    learningVelocity: 'Öğrenme Hızı',
    strongAreas: 'Güçlü Alanlar',
    improvementAreas: 'Geliştirilmesi Gereken Alanlar',
    recommendedNextCourse: 'Önerilen Sonraki Kurs',
    confidence: 'Güven',
    startCourse: 'Kursu Başlat',
    identifiedSkillGaps: 'Belirlenen Beceri Eksiklikleri',
    optimizedPathSuggestions: 'Optimize Edilmiş Yol Önerileri',
    refreshRecommendations: 'Önerileri Yenile',
    addToPath: 'Yola Ekle',
    priority: 'Öncelik',
    detectedLearningStyle: 'Tespit Edilen Öğrenme Stili',
    optimalLearningPace: 'Optimal Öğrenme Hızı',
    pathView: 'Yol Görünümü',
    recommendationsUpdated: 'Öneriler Güncellendi',
    adaptiveRecommendationsGenerated: 'Yeni uyarlanabilir öneriler oluşturuldu',
    successRate: 'Başarı Oranı',
    
    // Adaptive Learning Demo
    adaptiveLearningPathVisualization: 'Uyarlanabilen Öğrenme Yolu Görselleştirmesi',
    adaptiveLearningDescription: 'İlerlemenize, öğrenme tarzınıza ve hedeflerinize uyum sağlayan yapay zeka destekli kişiselleştirilmiş öğrenme yollarını deneyimleyin.',
    aiPoweredRecommendations: 'Yapay Zeka Destekli Öneriler',
    personalizedLearningPaths: 'Kişiselleştirilmiş Öğrenme Yolları',
    progressTracking: 'İlerleme Takibi',
    adaptiveInsights: 'Uyarlanabilen İçgörüler',
    selectLearningPath: 'Öğrenme Yolu Seçin',
    adaptivePathVisualization: 'Uyarlanabilen Yol Görselleştirmesi',
    pathId: 'Yol ID',
    howItWorks: 'Nasıl Çalışır',
    adaptiveFeatures: 'Uyarlanabilen Özellikler',
    analyticsFeatures: 'Analitik Özellikler',
    personalizedContentRecommendations: 'Kişiselleştirilmiş içerik önerileri',
    dynamicDifficultyAdjustment: 'Dinamik zorluk ayarı',
    learningStyleDetection: 'Öğrenme stili tespit',
    prerequisiteTracking: 'Ön koşul takibi',
    successProbabilityCalculation: 'Başarı olasılığı hesaplama',
    timeSpentTracking: 'Harcanan süre takibi',
    performanceAnalytics: 'Performans analitikleri',
    learningVelocityMeasurement: 'Öğrenme hızı ölçümü',
    skillGapIdentification: 'Beceri açığı belirleme',
    improvementRecommendations: 'Gelişim önerileri',
    authenticationRequired: 'Kimlik Doğrulama Gerekli',
    pleaseLoginToViewAdaptivePaths: 'Uyarlanabilir öğrenme yollarını görüntülemek için lütfen giriş yapın',
    
    // Advanced Adaptive Learning
    visualLearning: 'Görsel Öğrenme',
    auditoryLearning: 'İşitsel Öğrenme',
    kinestheticLearning: 'Kinestetik Öğrenme',
    readingWritingLearning: 'Okuma/Yazma Öğrenmesi',
    difficultyAdjustment: 'Zorluk Ayarlaması',
    currentDifficulty: 'Mevcut Zorluk',
    recommendedDifficulty: 'Önerilen Zorluk',
    increaseDifficulty: 'Zorluğu Artır',
    decreaseDifficulty: 'Zorluğu Azalt',
    maintainDifficulty: 'Mevcut Zorluğu Koru',
    applyAdjustment: 'Ayarlamayı Uygula',
    predictiveAnalytics: 'Tahminsel Analitikler',
    estimatedTimeToCompletion: 'Tahmini Tamamlanma Süresi',
    riskLevel: 'Risk Seviyesi',
    strugglingAreas: 'Zorluk Çekilen Alanlar',
    strengthAreas: 'Güçlü Alanlar',
    recommendedInterventions: 'Önerilen Müdahaleler',
    easy: 'Kolay',
    medium: 'Orta',
    hard: 'Zor',
    low: 'Düşük',
    high: 'Yüksek',
    normal: 'Normal',
    days: 'gün',
    actionable: 'Uygulanabilir',
    strength: 'Güçlü Yön',
    weakness: 'Zayıf Yön',
    opportunity: 'Fırsat',
    risk: 'Risk',
    recommendations: 'Öneriler',
    noInsightsAvailable: 'Henüz içgörü mevcut değil',
    insightsWillAppearAsYouProgress: 'Öğrenme yolculuğunuzda ilerledikçe içgörüler görünecek'

  }
};

// Type for the context value
interface LanguageContextType {
  language: Language;
  setLanguage: (language: Language) => void;
  t: (key: keyof typeof translations.en) => string;
}

// Create the context
const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

// Provider component
export function LanguageProvider({ children }: { children: ReactNode }) {
  // Get initially saved language or use 'en' as default
  const getSavedLanguage = (): Language => {
    try {
      const saved = localStorage.getItem('language');
      return (saved as Language) || 'en';
    } catch (error) {
      // In case of error (e.g., SSR or localStorage not available)
      return 'en';
    }
  };
  
  const [language, setLanguage] = useState<Language>(getSavedLanguage());

  // Update localStorage when language changes
  useEffect(() => {
    try {
      localStorage.setItem('language', language);
    } catch (error) {
      console.error('Could not save language preference:', error);
    }
  }, [language]);

  // Optimized translation function with useCallback for instant updates
  const t = useCallback((key: keyof typeof translations.en): string => {
    return (translations[language] as Record<string, string>)[key] || translations.en[key] || key;
  }, [language]);

  // Memoized context value to prevent unnecessary re-renders
  const value = useMemo(() => ({ language, setLanguage, t }), [language, t]);

  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
}

// Hook to use the language context
export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}