import { useState, useEffect } from 'react';
import { useForm } from 'react-hook-form';
import { zodResolver } from '@hookform/resolvers/zod';
import { z } from 'zod';
import { useMutation, useQuery } from '@tanstack/react-query';
import { queryClient, apiRequest } from '@/lib/queryClient';
import { useToast } from '@/hooks/use-toast';
import { useAuth } from '@/hooks/use-auth';
import { Card } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Textarea } from '@/components/ui/textarea';
import {
  Select, SelectContent, SelectItem, SelectTrigger, SelectValue
} from '@/components/ui/select';
import {
  Form, FormControl, FormDescription, FormField, FormItem, FormLabel, FormMessage
} from '@/components/ui/form';
import { Badge } from '@/components/ui/badge';
import { Slider } from '@/components/ui/slider';
import { Checkbox } from '@/components/ui/checkbox';
import {
  Target, BookOpen, Settings, Brain, Zap, Lightbulb, CheckCircle2, AlertCircle
} from 'lucide-react';

// Zod validation schema
const CurriculumGenerationFormSchema = z.object({
  name: z.string().min(3, 'Curriculum name must be at least 3 characters'),
  objectives: z.string().min(10, 'Learning objectives must be at least 10 characters'),
  selectedCourses: z.array(z.string()).min(1, 'Select at least one course'),
  timeCommitment: z.enum(['light', 'moderate', 'serious', 'intensive']),
  learningPace: z.enum(['slow', 'moderate', 'fast']),
  difficultyLevel: z.enum(['beginner', 'intermediate', 'advanced', 'expert']),
  personalizationLevel: z.number().min(0).max(100),
  creativityLevel: z.number().min(0).max(100),
  saveProduction: z.boolean(),
  allowAILearning: z.boolean()
});

type CurriculumFormData = z.infer<typeof CurriculumGenerationFormSchema>;

export default function CurriculumGenerationForm() {
  const { user } = useAuth();
  const { toast } = useToast();
  const [selectedCourses, setSelectedCourses] = useState<string[]>([]);
  const [aiSuggestions, setAiSuggestions] = useState<string[]>([]);
  const [showPreview, setShowPreview] = useState(false);

  // Fetch available courses
  const { data: courses = [] } = useQuery<any[]>({
    queryKey: ['/api/courses'],
    enabled: !!user
  });

  // Generate curriculum mutation
  const generateMutation = useMutation({
    mutationFn: (data: CurriculumFormData) =>
      apiRequest('POST', '/api/curriculum/generate', {
        title: data.name,
        objectives: data.objectives,
        selectedCourses: data.selectedCourses,
        preferences: {
          timeCommitment: data.timeCommitment,
          learningPace: data.learningPace,
          difficultyLevel: data.difficultyLevel
        },
        aiConfig: {
          personalizationLevel: data.personalizationLevel,
          creativityLevel: data.creativityLevel
        },
        saveProduction: data.saveProduction,
        allowAILearning: data.allowAILearning
      }),
    onSuccess: (result) => {
      toast({
        title: 'Success',
        description: 'Curriculum generated successfully!'
      });
      queryClient.invalidateQueries({ queryKey: ['/api/curriculum/list'] });
      form.reset();
      setSelectedCourses([]);
    },
    onError: (error: any) => {
      toast({
        title: 'Error',
        description: error.message || 'Failed to generate curriculum',
        variant: 'destructive'
      });
    }
  });

  // Generate AI suggestions for name
  const generateNameSuggestions = async (objectives: string) => {
    if (!objectives || objectives.length < 10) return;
    try {
      const response = await apiRequest('POST', '/api/ai/suggestions', {
        type: 'curriculum_name',
        context: objectives
      }) as any;
      if (response?.suggestions) {
        setAiSuggestions(response.suggestions);
      }
    } catch (error) {
      console.error('Failed to generate suggestions:', error);
    }
  };

  // Generate AI objectives
  const generateAIObjectives = async (name: string) => {
    if (!name || name.length < 3) return;
    try {
      const response = await apiRequest('POST', '/api/ai/suggestions', {
        type: 'learning_objectives',
        context: name
      }) as any;
      if (response?.suggestion) {
        form.setValue('objectives', response.suggestion);
        toast({
          title: 'AI Generated',
          description: 'Learning objectives generated by AI'
        });
      }
    } catch (error) {
      console.error('Failed to generate objectives:', error);
    }
  };

  const form = useForm<CurriculumFormData>({
    resolver: zodResolver(CurriculumGenerationFormSchema),
    defaultValues: {
      name: '',
      objectives: '',
      selectedCourses: [],
      timeCommitment: 'moderate',
      learningPace: 'moderate',
      difficultyLevel: 'intermediate',
      personalizationLevel: 75,
      creativityLevel: 60,
      saveProduction: true,
      allowAILearning: true
    }
  });

  const onSubmit = (data: CurriculumFormData) => {
    generateMutation.mutate(data);
  };

  const toggleCourse = (courseId: string) => {
    setSelectedCourses(prev => 
      prev.includes(courseId)
        ? prev.filter(id => id !== courseId)
        : [...prev, courseId]
    );
    form.setValue('selectedCourses', 
      selectedCourses.includes(courseId)
        ? selectedCourses.filter(id => id !== courseId)
        : [...selectedCourses, courseId]
    );
  };

  return (
    <div className="w-full min-h-screen bg-gradient-to-br from-blue-50 to-indigo-50 p-6">
      <div className="max-w-6xl mx-auto space-y-6">
        {/* Header */}
        <div className="space-y-2">
          <div className="flex items-center gap-3">
            <Brain className="w-8 h-8 text-blue-600" />
            <h1 className="text-4xl font-bold">Generate Your Curriculum</h1>
          </div>
          <p className="text-gray-600">Create a personalized learning path with AI guidance</p>
        </div>

        {/* Main Form */}
        <Form {...form}>
          <form onSubmit={form.handleSubmit(onSubmit)} className="space-y-6">
            {/* Section 1: Basic Information */}
            <Card className="p-6">
              <div className="flex items-center gap-2 mb-4">
                <Target className="w-5 h-5 text-blue-600" />
                <h2 className="text-2xl font-bold">Curriculum Goals</h2>
              </div>

              <div className="space-y-4">
                <FormField
                  control={form.control}
                  name="name"
                  render={({ field }) => (
                    <FormItem>
                      <FormLabel>Curriculum Name</FormLabel>
                      <FormControl>
                        <Input
                          placeholder="Enter a descriptive name (e.g., 'Advanced Python for Web Dev')"
                          {...field}
                          onChange={(e) => {
                            field.onChange(e);
                            generateNameSuggestions(form.getValues('objectives'));
                          }}
                          data-testid="input-curriculum-name"
                        />
                      </FormControl>
                      <FormMessage />
                      {aiSuggestions.length > 0 && (
                        <div className="mt-2 flex flex-wrap gap-2">
                          {aiSuggestions.map((suggestion, idx) => (
                            <Badge
                              key={idx}
                              variant="outline"
                              className="cursor-pointer hover:bg-blue-100"
                              onClick={() => form.setValue('name', suggestion)}
                              data-testid={`badge-name-suggestion-${idx}`}
                            >
                              {suggestion}
                            </Badge>
                          ))}
                        </div>
                      )}
                    </FormItem>
                  )}
                />

                <FormField
                  control={form.control}
                  name="objectives"
                  render={({ field }) => (
                    <FormItem>
                      <FormLabel>Learning Objectives</FormLabel>
                      <FormControl>
                        <Textarea
                          placeholder="Describe what you want to achieve... (e.g., 'Master full-stack web development with React and Node.js')"
                          className="min-h-24"
                          {...field}
                          data-testid="textarea-learning-objectives"
                        />
                      </FormControl>
                      <FormDescription>
                        Be specific about your goals. This helps AI generate better recommendations.
                      </FormDescription>
                      <Button
                        type="button"
                        variant="outline"
                        size="sm"
                        className="mt-2 gap-2"
                        onClick={() => generateAIObjectives(form.getValues('name'))}
                        disabled={!form.getValues('name')}
                        data-testid="button-generate-objectives"
                      >
                        <Lightbulb className="w-4 h-4" />
                        AI Generate Objectives
                      </Button>
                      <FormMessage />
                    </FormItem>
                  )}
                />
              </div>
            </Card>

            {/* Section 2: Course Selection */}
            <Card className="p-6">
              <div className="flex items-center gap-2 mb-4">
                <BookOpen className="w-5 h-5 text-green-600" />
                <h2 className="text-2xl font-bold">Course Selection</h2>
              </div>

              <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
                {/* Available Courses */}
                <div>
                  <h3 className="font-semibold mb-3">Available Courses</h3>
                  <div className="space-y-2 max-h-96 overflow-y-auto">
                    {courses.map((course: any) => (
                      <div
                        key={course.id}
                        className={`p-3 border rounded-lg cursor-pointer transition ${
                          selectedCourses.includes(course.id)
                            ? 'bg-blue-50 border-blue-300'
                            : 'bg-white hover:bg-gray-50'
                        }`}
                        onClick={() => toggleCourse(course.id)}
                        data-testid={`card-course-${course.id}`}
                      >
                        <div className="flex items-start justify-between">
                          <div className="flex-1">
                            <p className="font-medium text-sm">{course.titleEn || course.title}</p>
                            <p className="text-xs text-gray-500">{course.level} • {course.durationHours}h</p>
                          </div>
                          <Checkbox
                            checked={selectedCourses.includes(course.id)}
                            onChange={() => toggleCourse(course.id)}
                            data-testid={`checkbox-course-${course.id}`}
                          />
                        </div>
                      </div>
                    ))}
                  </div>
                </div>

                {/* Selected Courses */}
                <div>
                  <h3 className="font-semibold mb-3">Selected Courses ({selectedCourses.length})</h3>
                  {selectedCourses.length > 0 ? (
                    <div className="space-y-2 max-h-96 overflow-y-auto">
                      {courses
                        .filter((c: any) => selectedCourses.includes(c.id))
                        .map((course: any, idx: number) => (
                          <div
                            key={course.id}
                            className="p-3 bg-blue-50 border border-blue-300 rounded-lg flex items-start justify-between"
                            data-testid={`card-selected-course-${idx}`}
                          >
                            <div className="flex items-start gap-3">
                              <div className="font-semibold text-blue-600">{idx + 1}</div>
                              <div>
                                <p className="font-medium text-sm">{course.titleEn || course.title}</p>
                                <p className="text-xs text-gray-600">{course.durationHours}h</p>
                              </div>
                            </div>
                            <Button
                              type="button"
                              variant="ghost"
                              size="sm"
                              onClick={() => toggleCourse(course.id)}
                              data-testid={`button-remove-course-${idx}`}
                            >
                              ✕
                            </Button>
                          </div>
                        ))}
                    </div>
                  ) : (
                    <div className="p-6 text-center text-gray-500 bg-gray-50 rounded-lg">
                      No courses selected yet
                    </div>
                  )}
                </div>
              </div>

              <FormField
                control={form.control}
                name="selectedCourses"
                render={() => (
                  <FormItem className="mt-4">
                    <FormMessage />
                  </FormItem>
                )}
              />
            </Card>

            {/* Section 3: Learning Preferences */}
            <Card className="p-6">
              <div className="flex items-center gap-2 mb-4">
                <Settings className="w-5 h-5 text-orange-600" />
                <h2 className="text-2xl font-bold">Learning Preferences</h2>
              </div>

              <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
                <FormField
                  control={form.control}
                  name="timeCommitment"
                  render={({ field }) => (
                    <FormItem>
                      <FormLabel>Weekly Time Commitment</FormLabel>
                      <Select value={field.value} onValueChange={field.onChange}>
                        <FormControl>
                          <SelectTrigger data-testid="select-time-commitment">
                            <SelectValue />
                          </SelectTrigger>
                        </FormControl>
                        <SelectContent>
                          <SelectItem value="light">1-5 hours</SelectItem>
                          <SelectItem value="moderate">5-15 hours</SelectItem>
                          <SelectItem value="serious">15-25 hours</SelectItem>
                          <SelectItem value="intensive">25+ hours</SelectItem>
                        </SelectContent>
                      </Select>
                      <FormMessage />
                    </FormItem>
                  )}
                />

                <FormField
                  control={form.control}
                  name="learningPace"
                  render={({ field }) => (
                    <FormItem>
                      <FormLabel>Learning Pace</FormLabel>
                      <Select value={field.value} onValueChange={field.onChange}>
                        <FormControl>
                          <SelectTrigger data-testid="select-learning-pace">
                            <SelectValue />
                          </SelectTrigger>
                        </FormControl>
                        <SelectContent>
                          <SelectItem value="slow">Slow & Thorough</SelectItem>
                          <SelectItem value="moderate">Balanced Pace</SelectItem>
                          <SelectItem value="fast">Fast Track</SelectItem>
                        </SelectContent>
                      </Select>
                      <FormMessage />
                    </FormItem>
                  )}
                />

                <FormField
                  control={form.control}
                  name="difficultyLevel"
                  render={({ field }) => (
                    <FormItem>
                      <FormLabel>Target Difficulty</FormLabel>
                      <Select value={field.value} onValueChange={field.onChange}>
                        <FormControl>
                          <SelectTrigger data-testid="select-difficulty-level">
                            <SelectValue />
                          </SelectTrigger>
                        </FormControl>
                        <SelectContent>
                          <SelectItem value="beginner">Beginner</SelectItem>
                          <SelectItem value="intermediate">Intermediate</SelectItem>
                          <SelectItem value="advanced">Advanced</SelectItem>
                          <SelectItem value="expert">Expert</SelectItem>
                        </SelectContent>
                      </Select>
                      <FormMessage />
                    </FormItem>
                  )}
                />
              </div>
            </Card>

            {/* Section 4: AI Configuration */}
            <Card className="p-6">
              <div className="flex items-center gap-2 mb-4">
                <Brain className="w-5 h-5 text-purple-600" />
                <h2 className="text-2xl font-bold">AI Configuration</h2>
              </div>

              <div className="space-y-6">
                <FormField
                  control={form.control}
                  name="personalizationLevel"
                  render={({ field }) => (
                    <FormItem>
                      <FormLabel className="flex items-center justify-between">
                        <span>AI Personalization Level</span>
                        <Badge variant="outline">{field.value}%</Badge>
                      </FormLabel>
                      <FormControl>
                        <Slider
                          min={0}
                          max={100}
                          step={5}
                          value={[field.value]}
                          onValueChange={(value) => field.onChange(value[0])}
                          className="w-full"
                          data-testid="slider-personalization"
                        />
                      </FormControl>
                      <FormDescription>
                        Higher values = more tailored to your specific context
                      </FormDescription>
                    </FormItem>
                  )}
                />

                <FormField
                  control={form.control}
                  name="creativityLevel"
                  render={({ field }) => (
                    <FormItem>
                      <FormLabel className="flex items-center justify-between">
                        <span>AI Creativity</span>
                        <Badge variant="outline">{field.value}%</Badge>
                      </FormLabel>
                      <FormControl>
                        <Slider
                          min={0}
                          max={100}
                          step={5}
                          value={[field.value]}
                          onValueChange={(value) => field.onChange(value[0])}
                          className="w-full"
                          data-testid="slider-creativity"
                        />
                      </FormControl>
                      <FormDescription>
                        Higher values = more innovative and unique suggestions
                      </FormDescription>
                    </FormItem>
                  )}
                />

                <div className="space-y-3">
                  <FormField
                    control={form.control}
                    name="saveProduction"
                    render={({ field }) => (
                      <FormItem className="flex items-center gap-2 space-y-0">
                        <FormControl>
                          <Checkbox
                            checked={field.value}
                            onCheckedChange={field.onChange}
                            data-testid="checkbox-save-production"
                          />
                        </FormControl>
                        <FormLabel className="font-normal cursor-pointer">
                          Save this production for future use
                        </FormLabel>
                      </FormItem>
                    )}
                  />

                  <FormField
                    control={form.control}
                    name="allowAILearning"
                    render={({ field }) => (
                      <FormItem className="flex items-center gap-2 space-y-0">
                        <FormControl>
                          <Checkbox
                            checked={field.value}
                            onCheckedChange={field.onChange}
                            data-testid="checkbox-allow-learning"
                          />
                        </FormControl>
                        <FormLabel className="font-normal cursor-pointer">
                          Allow AI to learn from this generation for better recommendations
                        </FormLabel>
                      </FormItem>
                    )}
                  />
                </div>
              </div>
            </Card>

            {/* Form Actions */}
            <div className="flex gap-3 justify-center pb-6">
              <Button
                type="submit"
                size="lg"
                className="gap-2"
                disabled={generateMutation.isPending}
                data-testid="button-generate-curriculum"
              >
                <Zap className="w-5 h-5" />
                {generateMutation.isPending ? 'Generating...' : 'Generate Curriculum'}
              </Button>

              <Button
                type="button"
                variant="outline"
                size="lg"
                onClick={() => form.reset()}
                data-testid="button-reset-form"
              >
                Reset Form
              </Button>

              <Button
                type="button"
                variant="outline"
                size="lg"
                onClick={() => setShowPreview(!showPreview)}
                data-testid="button-preview"
              >
                Preview
              </Button>
            </div>
          </form>
        </Form>
      </div>
    </div>
  );
}
