import { createContext, useContext, useState, useEffect, ReactNode, useMemo, useCallback } from "react";

export type Language = 'en' | 'tr';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string, fallback?: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

// Comprehensive consolidated translations for English and Turkish
const translations = {
  en: {
    // Common
    appName: 'EduLearn Platform',
    loading: 'Loading...',
    save: 'Save',
    cancel: 'Cancel',
    edit: 'Edit',
    delete: 'Delete',
    confirm: 'Confirm',
    back: 'Back',
    next: 'Next',
    previous: 'Previous',
    search: 'Search',
    filter: 'Filter',
    sort: 'Sort',
    refresh: 'Refresh',
    view: 'View',
    share: 'Share',
    
    // Navigation
    dashboard: 'Dashboard',
    courses: 'Courses',
    assignments: 'Assignments',
    calendar: 'Calendar',
    resources: 'Resources',
    achievements: 'Achievements',
    profile: 'Profile',
    adminPanel: 'Admin Panel',
    courseGenerator: 'AI Course Generator',
    learningTrails: 'Learning Trails',
    smartSuggestions: 'Smart Suggestions',
    advancedAILearning: 'Advanced AI Learning',
    entranceExams: 'Entrance Exams',
    learningPaths: 'Learning Paths',
    integrations: 'Integrations',
    googleDrive: 'Google Drive',
    googleMeet: 'Google Meet',
    googleCalendar: 'Google Calendar',
    
    // Auth
    login: 'Login',
    register: 'Register',
    username: 'Username',
    password: 'Password',
    confirmPassword: 'Confirm Password',
    displayName: 'Display Name',
    forgotPassword: 'Forgot Password?',
    noAccount: 'Don\'t have an account?',
    haveAccount: 'Already have an account?',
    loginNow: 'Login Now',
    registerNow: 'Register Now',
    logout: 'Logout',
    
    // Dashboard
    welcomeBack: 'Welcome back',
    yourProgress: 'Your Progress',
    enrolledCourses: 'Enrolled Courses',
    upcomingAssignments: 'Upcoming Assignments',
    viewAll: 'View All',
    enrolledIn: 'Enrolled in',
    course: 'Course',
    coursesPlural: 'Courses',
    continueLeaning: 'Continue Learning',
    completed: 'Completed',
    dueDate: 'Due Date',
    continueWhereverYouLeftOff: 'Continue learning where you left off',
    searchCoursesResources: 'Search courses, resources...',
    dailyChallenge: 'Daily Challenge',
    coursesInProgress: 'Courses in Progress',
    completedCourses: 'Completed Courses',
    pendingAssignments: 'Pending Assignments',
    continueText: 'Continue learning! Click to see all your courses or find new ones.',
    greatJob: 'Great job! Review completed courses or explore advanced topics.',
    timeToSubmit: 'Time to submit! Click to complete your assignments.',
    allCaughtUp: 'All caught up! Check for new assignments.',
    checkForNewAssignments: 'Check for new assignments.',
    amazingProgress: 'Amazing progress! View all achievements and unlock more.',
    startEarningAchievements: 'Start earning achievements by completing challenges!',
    yourAchievements: 'Your Achievements',
    levelUpYourLearning: 'Level up your learning journey',
    
    // Study Management
    yourMentor: 'Your Mentor',
    aiMentor: 'AI Mentor',
    humanMentor: 'Human Mentor',
    specialization: 'Specialization',
    assignedOn: 'Assigned on',
    assigningMentor: 'Assigning your mentor...',
    mentorWillBeAssigned: 'A mentor will be assigned to help you succeed.',
    weeklyProgress: 'Weekly Progress',
    studyHours: 'Study Hours',
    adherenceScore: 'Adherence Score',
    targetAchieved: 'Target Achieved! 🎉',
    keepGoing: 'Keep going! 💪',
    studyPrograms: 'Study Programs',
    week: 'Week',
    viewAllPrograms: 'View All Programs',
    yourLevel: 'Your Level',
    progressToLevel: 'Progress to Level',
    completeChallengesToUnlock: 'Complete challenges to unlock your level!',
    activeChallenges: 'Active Challenges',
    noActiveChallenges: 'No active challenges',
    startChallenge: 'Start Challenge',
    recentAchievements: 'Recent Achievements',
    noAchievementsYet: 'No achievements yet',
    completeCoursesAndChallenges: 'Complete courses and challenges to earn achievements!',
    viewChallenges: 'View Challenges',
    leaderboards: 'Leaderboards',
    quickChallenge: 'Quick Challenge',
    pickUpWhereYouLeftOff: 'Pick up where you left off - your courses are waiting below, or discover new ones!',
    noCourseInProgress: 'No courses in progress',
    readyToStartLearning: 'Ready to start learning? Browse our course catalog and enroll in a course that interests you!',
    exploreCourses: 'Explore Courses',
    getAIRecommendations: 'Get AI Recommendations',
    recommendedForYou: 'Recommended For You',
    aiPoweredSuggestions: 'AI-powered course suggestions based on your interests and learning progress - perfect next steps for your journey!',
    perfectNextSteps: 'perfect next steps for your journey!',
    
    // Courses
    allCourses: 'All Courses',
    availableCourses: 'Available Courses',
    enrolled: 'Enrolled',
    myCourses: 'My Courses',
    inProgress: 'In Progress',
    continueButton: 'Continue',
    noCourses: 'No courses available',
    courseDuration: 'Duration',
    courseModules: 'Modules',
    hours: 'hours',
    searchPlaceholder: 'Search courses...',
    enrollmentSuccessful: 'Enrollment Successful',
    enrollmentFailed: 'Enrollment Failed',
    enrollmentSuccessDescription: 'You have successfully enrolled in the course',
    enrollmentFailedDescription: 'Failed to enroll in the course',
    manageLearningJourney: 'Manage your learning journey',
    noCoursesFound: 'No courses found',
    noCoursesFoundDescription: 'You haven\'t enrolled in any courses yet. Explore available courses to start your learning journey.',
    noCourseMatches: 'No courses match your search criteria.',
    noAvailableCourses: 'No courses available at the moment.',
    checkBackLater: 'Check back later for new courses.',
    tryDifferentSearch: 'Try a different search term.',
    module: 'Module',
    aiPersonalization: 'AI Personalization',
    personalizedForYou: 'Personalized For You',
    learningObjectives: 'Learning Objectives',
    aiAdaptedContent: 'AI-Adapted Content',
    selectLessonForContent: 'Select a lesson to see AI-personalized content',
    personalizedContentAvailable: 'Personalized content available',
    
    // Course Generator
    generateCourse: 'Generate Course',
    courseTitle: 'Course Title',
    courseDescription: 'Course Description',
    courseCategory: 'Category',
    topicInput: 'Topic',
    generateCourseButton: 'Generate Course',
    courseGenerated: 'Course Generated Successfully',
    saveCourse: 'Save Course',
    
    // Course Detail
    courseOverview: 'Course Overview',
    moduleOverview: 'Module Overview',
    lessonContent: 'Lesson Content',
    prerequisites: 'Prerequisites',
    learningOutcomes: 'Learning Outcomes',
    difficultyLevel: 'Difficulty Level',
    estimatedDuration: 'Estimated Duration',
    completionRate: 'Completion Rate',
    
    // Lesson Page
    lessonNotFound: 'Lesson Not Found',
    lessonNotFoundDescription: 'The lesson you are looking for does not exist or has not been created yet.',
    backToCourse: 'Back to Course',
    personalizedIntro: 'AI Personalized Introduction',
    practiceExercises: 'Practice Exercises',
    nextSteps: 'Next Steps',
    completeLesson: 'Complete Lesson',
    nextLesson: 'Next Lesson',
    previousLesson: 'Previous Lesson',
    minutes: 'minutes',
    levelInput: 'Level',
    targetAudienceInput: 'Target Audience',
    specificFocusInput: 'Specific Focus',
    generatingCourse: 'Generating course...',
    generateButton: 'Generate',
    
    // Assignments
    assignmentsDue: 'Assignments Due',
    noAssignments: 'No upcoming assignments',
    submitAssignment: 'Submit Assignment',
    viewDetails: 'View Details',
    
    // Calendar
    monthlyView: 'Monthly View',
    upcoming: 'Upcoming',
    noEvents: 'No events on this date',
    hasAssignments: 'assignments',
    selectDate: 'Select a date',
    
    // Admin
    adminDashboard: 'Admin Dashboard',
    manageUsers: 'Manage Users',
    manageCourses: 'Manage Courses',
    addTurkishCourses: 'Add Turkish Courses',
    
    // Turkish Exam Courses
    turkishCoursesAdded: 'Turkish courses added successfully',
    tyt: 'TYT',
    ayt: 'AYT',
    ydt: 'YDT',
    
    // Smart Suggestions Page
    smartSuggestionsDesc: "Get inspired with AI-powered suggestions! Discover trending goals, popular fields, and hot topics to guide your learning journey and make informed choices.",
    trendingGoals: "Trending Goals",
    popularLearningObjectives: "Popular learning objectives",
    popularFields: "Popular Fields",
    inDemandCareerAreas: "In-demand career areas",
    hotTopics: "Hot Topics",
    coursesGainingTraction: "Courses gaining traction",
    createYourLearningPath: "Create Your Learning Path",
    createYourLearningPathDesc: "Select your preferences to generate a personalized learning path",
    learningGoal: "Learning Goal",
    selectALearningGoal: "Select a learning goal",
    whatDoYouWantToAchieve: "What do you want to achieve?",
    careerField: "Career Field",
    selectOrEnterACareerField: "Select or enter a career field",
    yourFieldOfInterest: "Your field of interest",
    courseTopic: "Course Topic",
    selectATopic: "Select a topic",
    whatWouldYouLikeToLearn: "What would you like to learn?",
    timeframe: "Timeframe",
    selectATimeframe: "Select a timeframe",
    howLongDoYouWantToSpend: "How long do you want to spend?",
    generateLearningPath: "Generate Learning Path",
    howSmartSuggestionsWork: "How Smart Suggestions Work",
    howSmartSuggestionsWorkDesc: "Our suggestion system uses a combination of popular choices, trending topics, and personalized recommendations to help you navigate your educational journey.",
    learningGoalsInfo: "Choose from popular learning paths or enter your own custom goal to tailor your experience.",
    careerFieldsInfo: "Select your industry or field of interest to get relevant course recommendations.",
    courseTopicsInfo: "Browse trending topics or search for specific subjects you want to master.",
    loadingSuggestions: "Loading suggestions...",
    selectAnOption: "Select an option",
    searchOrSelectAnOption: "Search or select an option",
    
    // Control Panel translations
    studentControlPanel: "Student Control Panel",
    mentorControlPanel: "Mentor Control Panel", 
    manageYourLearningJourney: "Manage your learning journey and track your progress",
    trackAndGuideYourStudents: "Track and guide your students' learning progress",
    mentor: "Mentor",
    overview: "Overview",
    students: "Students",
    activities: "Activities",
    messaging: "Messaging",
    totalStudyHours: "Total Study Hours",
    coursesCompleted: "Courses Completed",
    currentStreak: "Current Streak",
    averageGrade: "Average Grade",
    days: "days",
    myLearningPaths: "My Learning Paths",
    createNewPath: "Create New Path",
    noLearningPaths: "No Learning Paths Yet",
    createFirstPath: "Create your first learning path to get started with personalized learning.",
    createLearningPath: "Create Learning Path",
    learningPathDeleted: "Learning Path Deleted",
    error: "Error",
    learningPathDeleteError: "Failed to delete learning path.",
    confirmDelete: "Are you sure you want to delete this learning path?",
    yourStudyActivityOverTime: "Your study activity over the past week",
    assignmentsDueSoon: "Your assignments and their due dates",
    noUpcomingAssignments: "No upcoming assignments",
    myAchievements: "My Achievements",
    recentAchievementsAndBadges: "Recent achievements and badges you've earned",
    totalStudents: "Total Students",
    activeStudents: "Active Students",
    weeklyStudyHours: "Weekly Study Hours",
    studentsNeedingAttention: "Students Needing Attention",
    studentsWithLowGradesOrInactivity: "Students with low grades or recent inactivity",
    topPerformers: "Top Performers",
    
    // Subscription Management
    subscriptionManagement: "Subscription Management",
    currentPlan: "Current Plan",
    freePlan: "Free Plan",
    premiumPlan: "Premium Plan",
    upgradeToPremium: "Upgrade to Premium",
    manageSubscription: "Manage Subscription",
    billingHistory: "Billing History",
    usageStats: "Usage Statistics",
    dailyAssessmentLimit: "Daily Assessment Limit",
    unlimitedAccess: "Unlimited Access",
    advancedAnalytics: "Advanced Analytics",
    prioritySupport: "Priority Support",
    upgradeBenefits: "Premium Benefits",
    monthlyPrice: "Monthly Price",
    selectPlan: "Select Plan",
    upgradeNow: "Upgrade Now",
    cancelSubscription: "Cancel Subscription",
    renewSubscription: "Renew Subscription",
    subscriptionStatus: "Subscription Status",
    nextBilling: "Next Billing",
    paymentMethod: "Payment Method",
    updatePayment: "Update Payment Method",
    subscriptionUpgraded: "Subscription Upgraded!",
    subscriptionCancelled: "Subscription Cancelled",
    paymentSuccessful: "Payment Successful",
    paymentFailed: "Payment Failed",
    limitReached: "Daily Limit Reached",
    limitReachedDesc: "You've reached your daily assessment limit. Upgrade to Premium for unlimited access.",
    assessmentsUsed: "Assessments Used Today",
    assessmentsRemaining: "Assessments Remaining",
    learningPathDeletedDesc: "Your learning path has been deleted successfully.",
    
    // Advanced Features
    adaptiveLearning: 'Adaptive Learning',
    adaptiveLearningPaths: 'Adaptive Learning Paths',
    personalizedRecommendations: 'Personalized Recommendations',
    skillGapAnalysis: 'Skill Gap Analysis',
    progressTracking: 'Progress Tracking',
    learningAnalytics: 'Learning Analytics',
    performanceMetrics: 'Performance Metrics',
    learningVelocityMeasurement: 'Learning velocity measurement',
    skillGapIdentification: 'Skill gap identification',
    improvementRecommendations: 'Improvement recommendations',
    authenticationRequired: 'Authentication Required',
    pleaseLoginToViewAdaptivePaths: 'Please login to view adaptive learning paths',
    
    // Advanced Adaptive Learning
    visualLearning: 'Visual Learning',
    auditoryLearning: 'Auditory Learning',
    kinestheticLearning: 'Kinesthetic Learning',
    readingWritingLearning: 'Reading/Writing Learning',
    difficultyAdjustment: 'Difficulty Adjustment',
    currentDifficulty: 'Current Difficulty',
    recommendedDifficulty: 'Recommended Difficulty',
    increaseDifficulty: 'Increase Difficulty',
    decreaseDifficulty: 'Decrease Difficulty',
    maintainDifficulty: 'Maintain Current Difficulty',
    applyAdjustment: 'Apply Adjustment',
    predictiveAnalytics: 'Predictive Analytics',
    estimatedTimeToCompletion: 'Estimated Time to Completion',
    riskLevel: 'Risk Level',
    strugglingAreas: 'Struggling Areas',
    strengthAreas: 'Strength Areas',
    recommendedInterventions: 'Recommended Interventions',
    easy: 'Easy',
    medium: 'Medium',
    hard: 'Hard',
    low: 'Low',
    high: 'High',
    normal: 'Normal',
    actionable: 'Actionable',
    strength: 'Strength',
    weakness: 'Weakness',
    opportunity: 'Opportunity',
    risk: 'Risk',
    noInsightsAvailable: 'No insights available yet',
    insightsWillAppearAsYouProgress: 'Insights will appear as you progress through your learning journey',
    
    // Error States
    unexpectedError: 'Something Went Wrong',
    errorBoundaryDescription: 'An unexpected error occurred. We apologize for the inconvenience.',
    errorDetails: 'Error Details',
    tryAgain: 'Try Again',
    goHome: 'Go Home',
    networkError: 'Network Error',
    networkErrorDesc: 'Please check your internet connection and try again.',
    serverError: 'Server Error',
    serverErrorDesc: 'Our servers are experiencing issues. Please try again in a moment.',
    permissionError: 'Access Denied',
    permissionErrorDesc: 'You do not have permission to access this resource.',
    notFoundError: 'Not Found',
    notFoundErrorDesc: 'The requested resource could not be found.',
    genericErrorDesc: 'An unexpected error occurred. Please try again.',
    failedToLoadCourses: 'Failed to load courses',
    coursesErrorDesc: 'Unable to load your courses. Please check your connection and try again.',
    failedToLoadAssignments: 'Failed to load assignments',
    assignmentsErrorDesc: 'Unable to load your assignments. Please try again.',
    
    // Loading States
    loadingCourses: 'Loading courses...',
    loadingAssignments: 'Loading assignments...',
    pleaseWait: 'Please wait...',
    retrying: 'Retrying...',
    
    // Empty States
    noCoursesTitle: 'No Courses Found',
    noCoursesDesc: 'Start your learning journey by exploring our course catalog.',
    noAssignmentsTitle: 'No Assignments',
    noAssignmentsDesc: 'You\'re all caught up! No pending assignments at the moment.',
    noAchievementsTitle: 'No Achievements Yet',
    noAchievementsDesc: 'Complete courses and challenges to unlock your first achievement!',
    noChallengesTitle: 'No Active Challenges',
    noChallengesDesc: 'Challenge yourself with skill-building exercises and competitions.',
    noSearchResultsTitle: 'No results found',
    noSearchResultsDesc: 'Try adjusting your search terms or browse our recommendations.',
    noDataTitle: 'No Data Available',
    noDataDesc: 'There\'s nothing to show here at the moment.',
    viewCourses: 'View Courses',
    startLearning: 'Start Learning',
    browseChallenges: 'Browse Challenges',
    clearSearch: 'Clear Search',
    
    // Additional Keys for Mixed Language Fix
    learningInterests: 'Learning Interests',
    addInterestsHelpText: 'Add your interests to get personalized course recommendations',
    aiStudyCompanion: 'AI Study Companion',
    viewAllCourses: 'View All Courses',
    personalizedRecommendationsDesc: 'Personalized recommendations based on your interests and learning history',
    
    // Course Recommendations Complete Keys
    courseRecommendations: 'Course Recommendations',
    basedOnInterestsAndHistory: 'Based on your interests and learning history',
    weWillRecommendCourses: 'We\'ll recommend courses as you continue learning. Take a few courses to get started!',
    aiGenerated: 'AI-Generated',
    enrolling: 'Enrolling...',
    enrollNow: 'Enroll Now',
    comingSoon: 'Coming soon!',
    
    // AI Assistant Complete Keys
    personalLearningAssistant: 'Your personal learning assistant',
    chat: 'Chat',
    tips: 'Tips',
    motivation: 'Motivation',
    courseContextActive: 'Course context active',
    lessonNumber: 'Lesson #',
    explainConcept: 'Explain concept',
    practiceProblem: 'Practice problem',
    studyTipsLabel: 'Study tips',
    reviewHelp: 'Review help',
    connectionError: 'Connection Error',
    connectionErrorDesc: 'I\'m having trouble connecting right now. Please try again.',
    chatCleared: 'Chat Cleared',
    chatClearedDesc: 'Your conversation history has been cleared.',
    failedToClearChat: 'Failed to clear chat history.',
    personalizedStudyTips: 'Personalized Study Tips',
    refreshLabel: 'Refresh',
    dailyMotivation: 'Daily Motivation',
    newMessage: 'New Message',
    personalizedStudyTipsDesc: 'Personalized study tips will appear here based on your progress',
    dailyMotivationDesc: 'Your daily motivation message will appear here',
    askMeAnything: 'Ask me anything about your studies...',
    welcomeMessage: 'Hello {name}! 👋 I\'m your AI Study Companion. I\'m here to help you with your coursework, explain concepts, provide study tips, and support your learning journey.\\n\\nHow can I assist you today?',
    troubleConnecting: 'I\'m experiencing some technical difficulties. Please try rephrasing your question or try again in a moment.',
    chatHistoryCleared: 'Chat history cleared! How can I help you with your studies today?',
    
    // Complete Missing Keys
    enrolledSuccessfully: 'Enrolled successfully',
    enrolledDescription: 'You\'ve been enrolled in this course',
    failedToEnroll: 'Failed to enroll',
    failedToEnrollDesc: 'There was an error enrolling you in this course',
    explainConceptPrompt: 'Can you explain this concept in simple terms?',
    practiceProblemPrompt: 'Give me a practice problem to work on',
    studyTipsPrompt: 'What study strategies would you recommend?',
    reviewHelpPrompt: 'Help me review what I\'ve learned'
  },
  tr: {
    // Common
    appName: 'EduLearn Platformu',
    loading: 'Yükleniyor...',
    save: 'Kaydet',
    cancel: 'İptal',
    edit: 'Düzenle',
    delete: 'Sil',
    confirm: 'Onayla',
    back: 'Geri',
    next: 'İleri',
    previous: 'Önceki',
    search: 'Ara',
    filter: 'Filtrele',
    sort: 'Sırala',
    refresh: 'Yenile',
    view: 'Görüntüle',
    share: 'Paylaş',
    
    // Navigation
    dashboard: 'Gösterge Paneli',
    courses: 'Kurslar',
    assignments: 'Ödevler',
    calendar: 'Takvim',
    resources: 'Kaynaklar',
    achievements: 'Başarılar',
    profile: 'Profil',
    adminPanel: 'Admin Paneli',
    courseGenerator: 'Yapay Zeka Kurs Oluşturucu',
    learningTrails: 'Öğrenme Parkurları',
    smartSuggestions: 'Akıllı Öneriler',
    advancedAILearning: 'Gelişmiş AI Öğrenim',
    entranceExams: 'Giriş Sınavları',
    learningPaths: 'Öğrenme Yolları',
    integrations: 'Entegrasyonlar',
    googleDrive: 'Google Drive',
    googleMeet: 'Google Meet',
    googleCalendar: 'Google Takvim',
    
    // Auth
    login: 'Giriş Yap',
    register: 'Kayıt Ol',
    username: 'Kullanıcı Adı',
    password: 'Şifre',
    confirmPassword: 'Şifreyi Onayla',
    displayName: 'Görünen Ad',
    forgotPassword: 'Şifreni mi unuttun?',
    noAccount: 'Hesabınız yok mu?',
    haveAccount: 'Zaten hesabınız var mı?',
    loginNow: 'Şimdi Giriş Yap',
    registerNow: 'Şimdi Kayıt Ol',
    logout: 'Çıkış Yap',
    
    // Dashboard
    welcomeBack: 'Tekrar hoş geldiniz',
    yourProgress: 'İlerlemeniz',
    enrolledCourses: 'Kayıtlı Kurslar',
    upcomingAssignments: 'Yaklaşan Ödevler',
    viewAll: 'Tümünü Görüntüle',
    enrolledIn: 'Kayıtlı',
    course: 'Kurs',
    coursesPlural: 'Kurslar',
    continueLeaning: 'Öğrenmeye Devam Et',
    completed: 'Tamamlandı',
    dueDate: 'Bitiş Tarihi',
    continueWhereverYouLeftOff: 'Kaldığınız yerden öğrenmeye devam edin',
    searchCoursesResources: 'Kurs, kaynak ara...',
    dailyChallenge: 'Günlük Meydan Okuma',
    coursesInProgress: 'Devam Eden Kurslar',
    completedCourses: 'Tamamlanan Kurslar',
    pendingAssignments: 'Bekleyen Ödevler',
    continueText: 'Öğrenmeye devam et! Tüm kurslarını görmek veya yenilerini bulmak için tıkla.',
    greatJob: 'Harika iş! Tamamlanan kursları incele veya ileri konuları keşfet.',
    timeToSubmit: 'Teslim zamanı! Ödevlerini tamamlamak için tıkla.',
    allCaughtUp: 'Hepsi tamam! Yeni ödevleri kontrol et.',
    checkForNewAssignments: 'Yeni ödevleri kontrol et.',
    amazingProgress: 'İnanılmaz ilerleme! Tüm başarıları görüntüle ve daha fazlasını aç.',
    startEarningAchievements: 'Meydan okumaları tamamlayarak başarı kazanmaya başla!',
    yourAchievements: 'Başarıların',
    levelUpYourLearning: 'Öğrenme yolculuğunu seviye atla',
    
    // Study Management
    yourMentor: 'Danışmanınız',
    aiMentor: 'AI Danışman',
    humanMentor: 'İnsan Danışman',
    specialization: 'Uzmanlık',
    assignedOn: 'Atama tarihi',
    assigningMentor: 'Danışmanınız atanıyor...',
    mentorWillBeAssigned: 'Başarılı olmanız için bir danışman atanacak.',
    weeklyProgress: 'Haftalık İlerleme',
    studyHours: 'Çalışma Saatleri',
    adherenceScore: 'Uyum',
    targetAchieved: 'Hedef Başarıldı! 🎉',
    keepGoing: 'Devam et! 💪',
    studyPrograms: 'Çalışma Programları',
    week: 'Hafta',
    viewAllPrograms: 'Tüm Programları Görüntüle',
    yourLevel: 'Seviyeniz',
    progressToLevel: 'Seviye İlerlemesi',
    completeChallengesToUnlock: 'Seviyenizi açmak için meydan okumaları tamamlayın!',
    activeChallenges: 'Aktif Meydan Okumalar',
    noActiveChallenges: 'Aktif meydan okuma yok',
    startChallenge: 'Meydan Okuma Başlat',
    recentAchievements: 'Son Başarılar',
    noAchievementsYet: 'Henüz başarı yok',
    completeCoursesAndChallenges: 'Başarı kazanmak için kursları ve meydan okumaları tamamla!',
    viewChallenges: 'Meydan Okumaları Görüntüle',
    leaderboards: 'Sıralama Tabloları',
    quickChallenge: 'Hızlı Meydan Okuma',
    pickUpWhereYouLeftOff: 'Kaldığın yerden devam et - kursların seni aşağıda bekliyor, veya yenilerini keşfet!',
    noCourseInProgress: 'Devam eden kurs yok',
    readyToStartLearning: 'Öğrenmeye başlamaya hazır mısın? Kurs kataloğumuzu gözden geçir ve ilgini çeken bir kursa kaydol!',
    exploreCourses: 'Kursları Keşfet',
    getAIRecommendations: 'AI Önerileri Al',
    recommendedForYou: 'Sizin İçin Önerilen',
    aiPoweredSuggestions: 'İlgi alanların ve öğrenme ilerlemen temelinde yapay zeka destekli kurs önerileri - yolculuğun için mükemmel sonraki adımlar!',
    perfectNextSteps: 'yolculuğun için mükemmel sonraki adımlar!',
    
    // Courses
    allCourses: 'Tüm Kurslar',
    availableCourses: 'Mevcut Kurslar',
    enrolled: 'Kayıtlı',
    myCourses: 'Kurslarım',
    inProgress: 'Devam Eden',
    continueButton: 'Devam Et',
    noCourses: 'Mevcut kurs yok',
    courseDuration: 'Süre',
    courseModules: 'Modüller',
    hours: 'saat',
    searchPlaceholder: 'Kurs ara...',
    enrollmentSuccessful: 'Kayıt Başarılı',
    enrollmentFailed: 'Kayıt Başarısız',
    enrollmentSuccessDescription: 'Kursa başarıyla kaydoldunuz',
    enrollmentFailedDescription: 'Kursa kaydolma işlemi başarısız oldu',
    manageLearningJourney: 'Öğrenme yolculuğunuzu yönetin',
    noCoursesFound: 'Kurs bulunamadı',
    noCoursesFoundDescription: 'Henüz herhangi bir kursa kaydolmadınız. Öğrenme yolculuğunuzu başlatmak için mevcut kursları keşfedin.',
    noCourseMatches: 'Arama kriterlerinizle eşleşen kurs bulunamadı.',
    noAvailableCourses: 'Şu anda mevcut kurs yok.',
    checkBackLater: 'Yeni kurslar için daha sonra tekrar kontrol edin.',
    tryDifferentSearch: 'Farklı bir arama terimi deneyin.',
    module: 'Modül',
    aiPersonalization: 'AI Kişiselleştirme',
    personalizedForYou: 'Sizin İçin Kişiselleştirildi',
    learningObjectives: 'Öğrenme Hedefleri',
    aiAdaptedContent: 'AI Uyarlanmış İçerik',
    selectLessonForContent: 'AI-kişiselleştirilmiş içeriği görmek için bir ders seçin',
    personalizedContentAvailable: 'Kişiselleştirilmiş içerik mevcut',
    
    // Course Generator
    generateCourse: 'Kurs Oluştur',
    courseTitle: 'Kurs Başlığı',
    courseDescription: 'Kurs Açıklaması',
    courseCategory: 'Kategori',
    topicInput: 'Konu',
    generateCourseButton: 'Kurs Oluştur',
    courseGenerated: 'Kurs Başarıyla Oluşturuldu',
    saveCourse: 'Kursu Kaydet',
    
    // Course Detail
    courseOverview: 'Kurs Genel Bakış',
    moduleOverview: 'Modül Genel Bakış',
    lessonContent: 'Ders İçeriği',
    prerequisites: 'Ön Koşullar',
    learningOutcomes: 'Öğrenme Çıktıları',
    difficultyLevel: 'Zorluk Seviyesi',
    estimatedDuration: 'Tahmini Süre',
    completionRate: 'Tamamlanma Oranı',
    
    // Lesson Page
    lessonNotFound: 'Ders Bulunamadı',
    lessonNotFoundDescription: 'Aradığınız ders mevcut değil veya henüz oluşturulmadı.',
    backToCourse: 'Kursa Dön',
    personalizedIntro: 'AI Kişiselleştirilmiş Giriş',
    practiceExercises: 'Alıştırmalar',
    nextSteps: 'Sonraki Adımlar',
    completeLesson: 'Dersi Tamamla',
    nextLesson: 'Sonraki Ders',
    previousLesson: 'Önceki Ders',
    minutes: 'dakika',
    levelInput: 'Seviye',
    targetAudienceInput: 'Hedef Kitle',
    specificFocusInput: 'Özel Odak',
    generatingCourse: 'Kurs Oluşturuluyor...',
    generateButton: 'Oluştur',
    
    // Assignments
    assignmentsDue: 'Yaklaşan Ödevler',
    noAssignments: 'Yaklaşan ödev yok',
    submitAssignment: 'Ödevi Gönder',
    viewDetails: 'Detayları Görüntüle',
    
    // Calendar
    monthlyView: 'Aylık Görünüm',
    upcoming: 'Yaklaşan',
    noEvents: 'Bu tarihte etkinlik yok',
    hasAssignments: 'ödev var',
    selectDate: 'Bir tarih seçin',
    
    // Admin
    adminDashboard: 'Admin Gösterge Paneli',
    manageUsers: 'Kullanıcıları Yönet',
    manageCourses: 'Kursları Yönet',
    addTurkishCourses: 'YKS Kurslarını Ekle',
    
    // Turkish Exam Courses
    turkishCoursesAdded: 'YKS kursları başarıyla eklendi',
    tyt: 'TYT',
    ayt: 'AYT',
    ydt: 'YDT',
    
    // Smart Suggestions Page
    smartSuggestionsDesc: "AI destekli önerilerle ilham alın! Öğrenme yolculuğunuzu yönlendirecek trend hedefleri, popüler alanları ve sıcak konuları keşfedin.",
    trendingGoals: "Trend Hedefler",
    popularLearningObjectives: "Popüler öğrenme hedefleri",
    popularFields: "Popüler Alanlar",
    inDemandCareerAreas: "Talep gören kariyer alanları",
    hotTopics: "Sıcak Konular",
    coursesGainingTraction: "Ivme kazanan dersler",
    createYourLearningPath: "Öğrenme Yolunu Oluştur",
    createYourLearningPathDesc: "Kişiselleştirilmiş öğrenme yolu oluşturmak için tercihlerinizi seçin",
    learningGoal: "Öğrenme Hedefi",
    selectALearningGoal: "Bir öğrenme hedefi seçin",
    whatDoYouWantToAchieve: "Neyi başarmak istiyorsunuz?",
    careerField: "Kariyer Alanı",
    selectOrEnterACareerField: "Bir kariyer alanı seçin veya girin",
    yourFieldOfInterest: "İlgilendiğiniz alan",
    courseTopic: "Ders Konusu",
    selectATopic: "Bir konu seçin",
    whatWouldYouLikeToLearn: "Neyi öğrenmek istersiniz?",
    timeframe: "Zaman Dilimi",
    selectATimeframe: "Bir zaman dilimi seçin",
    howLongDoYouWantToSpend: "Ne kadar zaman ayırmak istiyorsunuz?",
    generateLearningPath: "Öğrenme Yolu Oluştur",
    howSmartSuggestionsWork: "Akıllı Öneriler Nasıl Çalışır",
    howSmartSuggestionsWorkDesc: "Öneri sistemimiz, eğitim yolculuğunuzda size rehberlik etmek için popüler seçimler, trend konular ve kişiselleştirilmiş önerilerin bir kombinasyonunu kullanır.",
    learningGoalsInfo: "Popüler öğrenme yollarından seçim yapın veya deneyiminizi özelleştirmek için kendi özel hedefinizi girin.",
    careerFieldsInfo: "İlgili ders önerileri almak için sektörünüzü veya ilgi alanınızı seçin.",
    courseTopicsInfo: "Trend konulara göz atın veya ustalaşmak istediğiniz belirli konuları arayın.",
    loadingSuggestions: "Öneriler yükleniyor...",
    selectAnOption: "Bir seçenek belirleyin",
    searchOrSelectAnOption: "Bir seçenek arayın veya seçin",
    
    // Control Panel translations
    studentControlPanel: "Öğrenci Kontrol Paneli",
    mentorControlPanel: "Mentor Kontrol Paneli",
    manageYourLearningJourney: "Öğrenme yolculuğunuzu yönetin ve ilerlemenizi takip edin",
    trackAndGuideYourStudents: "Öğrencilerinizin öğrenme ilerlemesini takip edin ve rehberlik edin",
    mentor: "Mentor",
    overview: "Genel Bakış",
    students: "Öğrenciler",
    activities: "Aktiviteler",
    messaging: "Mesajlaşma",
    totalStudyHours: "Toplam Ders Saatleri",
    coursesCompleted: "Tamamlanan Dersler",
    currentStreak: "Mevcut Seri",
    averageGrade: "Ortalama Not",
    days: "gün",
    myLearningPaths: "Öğrenme Yollarım",
    createNewPath: "Yeni Yol Oluştur",
    noLearningPaths: "Henüz Öğrenme Yolu Yok",
    createFirstPath: "Kişiselleştirilmiş öğrenmeye başlamak için ilk öğrenme yolunuzu oluşturun.",
    createLearningPath: "Öğrenme Yolu Oluştur",
    learningPathDeleted: "Öğrenme Yolu Silindi",
    error: "Hata",
    learningPathDeleteError: "Öğrenme yolu silinemedi.",
    confirmDelete: "Bu öğrenme yolunu silmek istediğinizden emin misiniz?",
    yourStudyActivityOverTime: "Geçen hafta boyunca ders aktiviteniz",
    assignmentsDueSoon: "Ödevleriniz ve teslim tarihleri",
    noUpcomingAssignments: "Yaklaşan ödev yok",
    myAchievements: "Başarılarım",
    recentAchievementsAndBadges: "Kazandığınız son başarılar ve rozetler",
    totalStudents: "Toplam Öğrenci",
    activeStudents: "Aktif Öğrenciler",
    weeklyStudyHours: "Haftalık Ders Saatleri",
    studentsNeedingAttention: "Dikkat Gerektiren Öğrenciler",
    studentsWithLowGradesOrInactivity: "Düşük notlu veya son zamanlarda aktif olmayan öğrenciler",
    topPerformers: "En İyi Performans Gösterenler",
    
    // Subscription Management
    subscriptionManagement: "Abonelik Yönetimi",
    currentPlan: "Mevcut Plan",
    freePlan: "Ücretsiz Plan",
    premiumPlan: "Premium Plan",
    upgradeToPremium: "Premium'a Yükselt",
    manageSubscription: "Aboneliği Yönet",
    billingHistory: "Fatura Geçmişi",
    usageStats: "Kullanım İstatistikleri",
    dailyAssessmentLimit: "Günlük Değerlendirme Limiti",
    unlimitedAccess: "Sınırsız Erişim",
    advancedAnalytics: "Gelişmiş Analitik",
    prioritySupport: "Öncelikli Destek",
    upgradeBenefits: "Premium Avantajları",
    monthlyPrice: "Aylık Ücret",
    selectPlan: "Plan Seç",
    upgradeNow: "Şimdi Yükselt",
    cancelSubscription: "Aboneliği İptal Et",
    renewSubscription: "Aboneliği Yenile",
    subscriptionStatus: "Abonelik Durumu",
    nextBilling: "Sonraki Faturalama",
    paymentMethod: "Ödeme Yöntemi",
    updatePayment: "Ödeme Yöntemini Güncelle",
    subscriptionUpgraded: "Abonelik Yükseltildi!",
    subscriptionCancelled: "Abonelik İptal Edildi",
    paymentSuccessful: "Ödeme Başarılı",
    paymentFailed: "Ödeme Başarısız",
    limitReached: "Günlük Limit Doldu",
    limitReachedDesc: "Günlük değerlendirme limitinize ulaştınız. Sınırsız erişim için Premium'a yükseltin.",
    assessmentsUsed: "Bugün Kullanılan Değerlendirmeler",
    assessmentsRemaining: "Kalan Değerlendirmeler",
    learningPathDeletedDesc: "Öğrenme yolunuz başarıyla silindi.",
    
    // Advanced Features
    adaptiveLearning: 'Uyarlanabilir Öğrenme',
    adaptiveLearningPaths: 'Uyarlanabilir Öğrenme Yolları',
    personalizedRecommendations: 'Kişiselleştirilmiş Öneriler',
    skillGapAnalysis: 'Beceri Açığı Analizi',
    progressTracking: 'İlerleme Takibi',
    learningAnalytics: 'Öğrenme Analitiği',
    performanceMetrics: 'Performans Metrikleri',
    learningVelocityMeasurement: 'Öğrenme hızı ölçümü',
    skillGapIdentification: 'Beceri açığı tanımlama',
    improvementRecommendations: 'İyileştirme önerileri',
    authenticationRequired: 'Kimlik Doğrulama Gerekli',
    pleaseLoginToViewAdaptivePaths: 'Uyarlanabilir öğrenme yollarını görüntülemek için lütfen giriş yapın',
    
    // Advanced Adaptive Learning
    visualLearning: 'Görsel Öğrenme',
    auditoryLearning: 'İşitsel Öğrenme',
    kinestheticLearning: 'Kinestetik Öğrenme',
    readingWritingLearning: 'Okuma/Yazma Öğrenmesi',
    difficultyAdjustment: 'Zorluk Ayarlaması',
    currentDifficulty: 'Mevcut Zorluk',
    recommendedDifficulty: 'Önerilen Zorluk',
    increaseDifficulty: 'Zorluğu Artır',
    decreaseDifficulty: 'Zorluğu Azalt',
    maintainDifficulty: 'Mevcut Zorluğu Koru',
    applyAdjustment: 'Ayarlamayı Uygula',
    predictiveAnalytics: 'Tahmine Dayalı Analitik',
    estimatedTimeToCompletion: 'Tahmini Tamamlanma Süresi',
    riskLevel: 'Risk Seviyesi',
    strugglingAreas: 'Zorlanılan Alanlar',
    strengthAreas: 'Güçlü Alanlar',
    recommendedInterventions: 'Önerilen Müdahaleler',
    easy: 'Kolay',
    medium: 'Orta',
    hard: 'Zor',
    low: 'Düşük',
    high: 'Yüksek',
    normal: 'Normal',
    actionable: 'Eylem Gerektiren',
    strength: 'Güçlü Yön',
    weakness: 'Zayıf Yön',
    opportunity: 'Fırsat',
    risk: 'Risk',
    noInsightsAvailable: 'Henüz içgörü mevcut değil',
    insightsWillAppearAsYouProgress: 'Öğrenme yolculuğunuz ilerledikçe içgörüler görünecek',
    
    // Error States
    unexpectedError: 'Bir Hata Oluştu',
    errorBoundaryDescription: 'Beklenmedik bir hata oluştu. Özür dileriz.',
    errorDetails: 'Hata Detayları',
    tryAgain: 'Tekrar Dene',
    goHome: 'Ana Sayfaya Git',
    networkError: 'Ağ Hatası',
    networkErrorDesc: 'Lütfen internet bağlantınızı kontrol edin ve tekrar deneyin.',
    serverError: 'Sunucu Hatası',
    serverErrorDesc: 'Sunucularımızda sorun yaşanıyor. Lütfen biraz sonra tekrar deneyin.',
    permissionError: 'Erişim Reddedildi',
    permissionErrorDesc: 'Bu kaynağa erişim yetkiniz yok.',
    notFoundError: 'Bulunamadı',
    notFoundErrorDesc: 'İstenen kaynak bulunamadı.',
    genericErrorDesc: 'Beklenmedik bir hata oluştu. Lütfen tekrar deneyin.',
    failedToLoadCourses: 'Kurslar yüklenemedi',
    coursesErrorDesc: 'Kurslarınız yüklenemedi. Lütfen bağlantınızı kontrol edin ve tekrar deneyin.',
    failedToLoadAssignments: 'Ödevler yüklenemedi',
    assignmentsErrorDesc: 'Ödevleriniz yüklenemedi. Lütfen tekrar deneyin.',
    
    // Loading States
    loadingCourses: 'Kurslar yükleniyor...',
    loadingAssignments: 'Ödevler yükleniyor...',
    pleaseWait: 'Lütfen bekleyin...',
    retrying: 'Yeniden deneniyor...',
    
    // Empty States
    noCoursesTitle: 'Kurs Bulunamadı',
    noCoursesDesc: 'Kurs kataloğumuzu keşfederek öğrenme yolculuğunuzu başlatın.',
    noAssignmentsTitle: 'Ödev Yok',
    noAssignmentsDesc: 'Harika! Şu anda bekleyen ödeviniz yok.',
    noAchievementsTitle: 'Henüz Başarı Yok',
    noAchievementsDesc: 'İlk başarınızı açmak için kursları ve meydan okumaları tamamlayın!',
    noChallengesTitle: 'Aktif Meydan Okuma Yok',
    noChallengesDesc: 'Beceri geliştiren egzersizler ve yarışmalarla kendinize meydan okuyun.',
    noSearchResultsTitle: 'Sonuç bulunamadı',
    noSearchResultsDesc: 'Arama terimlerinizi ayarlamayı deneyin veya önerilerimize göz atın.',
    noDataTitle: 'Veri Mevcut Değil',
    noDataDesc: 'Şu anda burada gösterilecek bir şey yok.',
    viewCourses: 'Kursları Görüntüle',
    startLearning: 'Öğrenmeye Başla',
    browseChallenges: 'Meydan Okumaları Gözat',
    clearSearch: 'Aramayı Temizle',
    
    // Additional Keys for Mixed Language Fix
    learningInterests: 'Öğrenme İlgi Alanları',
    addInterestsHelpText: 'Kişiselleştirilmiş kurs önerileri almak için ilgi alanlarınızı ekleyin',
    aiStudyCompanion: 'Yapay Zeka Çalışma Asistanı',
    viewAllCourses: 'Tüm Kursları Görüntüle',
    personalizedRecommendationsDesc: 'İlgi alanlarınız ve öğrenme geçmişiniz temelinde kişiselleştirilmiş öneriler',
    
    // Course Recommendations Complete Keys
    courseRecommendations: 'Kurs Önerileri',
    basedOnInterestsAndHistory: 'İlgi alanlarınız ve öğrenme geçmişiniz temelinde',
    weWillRecommendCourses: 'Öğrenmeye devam ederken kurslar önereceğiz. Başlamak için birkaç kursa katılın!',
    aiGenerated: 'Yapay Zeka Oluşturuldu',
    enrolling: 'Kaydolunuyor...',
    enrollNow: 'Şimdi Kaydol',
    comingSoon: 'Yakında!',
    
    // AI Assistant Complete Keys
    personalLearningAssistant: 'Kişisel öğrenme asistanınız',
    chat: 'Sohbet',
    tips: 'İpuçları',
    motivation: 'Motivasyon',
    courseContextActive: 'Kurs bağlamı etkin',
    lessonNumber: 'Ders #',
    explainConcept: 'Kavramı açıkla',
    practiceProblem: 'Alıştırma problemi',
    studyTipsLabel: 'Çalışma ipuçları',
    reviewHelp: 'İnceleme yardımı',
    connectionError: 'Bağlantı Hatası',
    connectionErrorDesc: 'Şu anda bağlanmakta zorlanıyorum. Lütfen tekrar deneyin.',
    chatCleared: 'Sohbet Temizlendi',
    chatClearedDesc: 'Konuşma geçmişiniz temizlendi.',
    failedToClearChat: 'Sohbet geçmişi temizlenemedi.',
    personalizedStudyTips: 'Kişiselleştirilmiş Çalışma İpuçları',
    refreshLabel: 'Yenile',
    dailyMotivation: 'Günlük Motivasyon',
    newMessage: 'Yeni Mesaj',
    personalizedStudyTipsDesc: 'İlerlemenize göre kişiselleştirilmiş çalışma ipuçları burada görünecek',
    dailyMotivationDesc: 'Günlük motivasyon mesajınız burada görünecek',
    askMeAnything: 'Çalışmalarınızla ilgili her şeyi sorabilirsiniz...',
    welcomeMessage: 'Merhaba {name}! 👋 Ben senin Yapay Zeka Çalışma Asistanınım. Ders çalışmanızda, kavramları açıklamada, çalışma ipuçları sunmada ve öğrenme yolculuğunuzu desteklemede buradayım.\\n\\nBugün nasıl yardımcı olabilirim?',
    troubleConnecting: 'Teknik zorluklarla karşılaşıyorum. Lütfen sorunuzu yeniden ifade edin veya biraz sonra tekrar deneyin.',
    chatHistoryCleared: 'Sohbet geçmişi temizlendi! Bugün çalışmalarınızda nasıl yardımcı olabilirim?',
    
    // Complete Missing Keys
    enrolledSuccessfully: 'Kayıt başarılı',
    enrolledDescription: 'Bu kursa başarıyla kaydoldunuz',
    failedToEnroll: 'Kayıt başarısız',
    failedToEnrollDesc: 'Kursa kaydolma işleminde bir hata oluştu',
    explainConceptPrompt: 'Bu kavramı basit terimlerle açıklayabilir misin?',
    practiceProblemPrompt: 'Üzerinde çalışabileceğim bir alıştırma problemi ver',
    studyTipsPrompt: 'Hangi çalışma stratejilerini önerirsin?',
    reviewHelpPrompt: 'Öğrendiklerimi gözden geçirmeme yardım et'
  }
};

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>(() => {
    // Initialize from localStorage or default to 'en'
    if (typeof window !== 'undefined') {
      const saved = localStorage.getItem('language');
      return (saved as Language) || 'en';
    }
    return 'en';
  });

  // Save to localStorage when language changes
  useEffect(() => {
    if (typeof window !== 'undefined') {
      localStorage.setItem('language', language);
    }
  }, [language]);

  // Translation function with fallback support
  const t = useCallback((key: string, fallback?: string): string => {
    const translation = translations[language]?.[key as keyof typeof translations['en']];
    if (translation) {
      return translation as string;
    }
    
    // Try English fallback
    const englishTranslation = translations.en[key as keyof typeof translations['en']];
    if (englishTranslation) {
      return englishTranslation as string;
    }
    
    // Return provided fallback or key
    return fallback || key;
  }, [language]);

  const contextValue = useMemo(() => ({
    language,
    setLanguage,
    t
  }), [language, t]);

  return (
    <LanguageContext.Provider value={contextValue}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}