import { createContext, useContext, useState, ReactNode } from "react";

interface LanguageContextType {
  language: 'en' | 'tr';
  setLanguage: (lang: 'en' | 'tr') => void;
  t: (key: string, fallback?: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

// Translation keys for suggestions demo
const translations = {
  en: {
    // Smart Suggestions Page
    smartSuggestions: "Smart Suggestions",
    smartSuggestionsDesc: "Get inspired with AI-powered suggestions! Discover trending goals, popular fields, and hot topics to guide your learning journey and make informed choices.",
    trendingGoals: "Trending Goals",
    popularLearningObjectives: "Popular learning objectives",
    popularFields: "Popular Fields",
    inDemandCareerAreas: "In-demand career areas",
    hotTopics: "Hot Topics",
    coursesGainingTraction: "Courses gaining traction",
    createYourLearningPath: "Create Your Learning Path",
    createYourLearningPathDesc: "Select your preferences to generate a personalized learning path",
    learningGoal: "Learning Goal",
    selectALearningGoal: "Select a learning goal",
    whatDoYouWantToAchieve: "What do you want to achieve?",
    careerField: "Career Field",
    selectOrEnterACareerField: "Select or enter a career field",
    yourFieldOfInterest: "Your field of interest",
    courseTopic: "Course Topic",
    selectATopic: "Select a topic",
    whatWouldYouLikeToLearn: "What would you like to learn?",
    timeframe: "Timeframe",
    selectATimeframe: "Select a timeframe",
    howLongDoYouWantToSpend: "How long do you want to spend?",
    generateLearningPath: "Generate Learning Path",
    // How it works section
    howSmartSuggestionsWork: "How Smart Suggestions Work",
    howSmartSuggestionsWorkDesc: "Our suggestion system uses a combination of popular choices, trending topics, and personalized recommendations to help you navigate your educational journey.",
    learningGoalsInfo: "Choose from popular learning paths or enter your own custom goal to tailor your experience.",
    careerFieldsInfo: "Select your industry or field of interest to get relevant course recommendations.",
    courseTopicsInfo: "Browse trending topics or search for specific subjects you want to master.",
    loadingSuggestions: "Loading suggestions...",
    selectAnOption: "Select an option",
    searchOrSelectAnOption: "Search or select an option",
    // Control Panel translations
    studentControlPanel: "Student Control Panel",
    mentorControlPanel: "Mentor Control Panel", 
    manageYourLearningJourney: "Manage your learning journey and track your progress",
    trackAndGuideYourStudents: "Track and guide your students' learning progress",
    student: "Student",
    mentor: "Mentor",
    overview: "Overview",
    learningPaths: "Learning Paths",
    progress: "Progress",
    assignments: "Assignments",
    achievements: "Achievements",
    students: "Students",
    activities: "Activities",
    messaging: "Messaging",
    totalStudyHours: "Total Study Hours",
    coursesCompleted: "Courses Completed",
    currentStreak: "Current Streak",
    averageGrade: "Average Grade",
    days: "days",
    myLearningPaths: "My Learning Paths",
    createNewPath: "Create New Path",
    noLearningPaths: "No Learning Paths Yet",
    createFirstPath: "Create your first learning path to get started with personalized learning.",
    createLearningPath: "Create Learning Path",
    viewDetails: "View Details",
    delete: "Delete",
    learningPathDeleted: "Learning Path Deleted",
    learningPathDeletedDesc: "Your learning path has been deleted successfully.",
    error: "Error",
    learningPathDeleteError: "Failed to delete learning path.",
    confirmDelete: "Are you sure you want to delete this learning path?",
    weeklyProgress: "Weekly Progress",
    yourStudyActivityOverTime: "Your study activity over the past week",
    upcomingAssignments: "Upcoming Assignments",
    assignmentsDueSoon: "Your assignments and their due dates",
    noUpcomingAssignments: "No upcoming assignments",
    myAchievements: "My Achievements",
    recentAchievementsAndBadges: "Recent achievements and badges you've earned",
    noAchievementsYet: "No achievements yet. Keep learning to earn your first badge!",
    totalStudents: "Total Students",
    activeStudents: "Active Students",
    weeklyStudyHours: "Weekly Study Hours",
    completionRate: "Completion Rate",
    studentsNeedingAttention: "Students Needing Attention",
    studentsWithLowGradesOrInactivity: "Students with low grades or recent inactivity",
    topPerformers: "Top Performers",
    studentsWithHighGrades: "Students excelling in their studies",
    contact: "Contact",
    allStudents: "All Students",
    completeOverviewOfAllStudents: "Complete overview of all your students and their progress",
    courses: "Courses",
    studyTime: "Study Time",
    streak: "Streak",
    lastActivity: "Last Activity",
    actions: "Actions",
    view: "View",
    recentActivities: "Recent Activities",
    latestStudentActivitiesAndProgress: "Latest student activities and progress updates",
    noRecentActivities: "No recent activities to display",
    sendMessage: "Send Message to Student",
    communicateDirectlyWithYourStudents: "Communicate directly with your students",
    selectStudent: "Select Student",
    chooseStudent: "Choose a student...",
    messagingTo: "Messaging to",
    message: "Message",
    typeYourMessage: "Type your message here...",
    sending: "Sending...",
    cancel: "Cancel",
    messageSent: "Message Sent",
    messagesSentSuccessfully: "Your message has been sent to the student.",
    failedToSendMessage: "Failed to send message. Please try again."
  },
  tr: {
    // Smart Suggestions Page
    smartSuggestions: "Akıllı Öneriler",
    smartSuggestionsDesc: "AI destekli önerilerle ilham alın! Öğrenme yolculuğunuzu yönlendirecek trend hedefleri, popüler alanları ve sıcak konuları keşfedin.",
    trendingGoals: "Trend Hedefler",
    popularLearningObjectives: "Popüler öğrenme hedefleri",
    popularFields: "Popüler Alanlar",
    inDemandCareerAreas: "Talep gören kariyer alanları",
    hotTopics: "Sıcak Konular",
    coursesGainingTraction: "Ivme kazanan dersler",
    createYourLearningPath: "Öğrenme Yolunu Oluştur",
    createYourLearningPathDesc: "Kişiselleştirilmiş öğrenme yolu oluşturmak için tercihlerinizi seçin",
    learningGoal: "Öğrenme Hedefi",
    selectALearningGoal: "Bir öğrenme hedefi seçin",
    whatDoYouWantToAchieve: "Neyi başarmak istiyorsunuz?",
    careerField: "Kariyer Alanı",
    selectOrEnterACareerField: "Bir kariyer alanı seçin veya girin",
    yourFieldOfInterest: "İlgilendiğiniz alan",
    courseTopic: "Ders Konusu",
    selectATopic: "Bir konu seçin",
    whatWouldYouLikeToLearn: "Neyi öğrenmek istersiniz?",
    timeframe: "Zaman Dilimi",
    selectATimeframe: "Bir zaman dilimi seçin",
    howLongDoYouWantToSpend: "Ne kadar zaman ayırmak istiyorsunuz?",
    generateLearningPath: "Öğrenme Yolu Oluştur",
    // How it works section
    howSmartSuggestionsWork: "Akıllı Öneriler Nasıl Çalışır",
    howSmartSuggestionsWorkDesc: "Öneri sistemimiz, eğitim yolculuğunuzda size rehberlik etmek için popüler seçimler, trend konular ve kişiselleştirilmiş önerilerin bir kombinasyonunu kullanır.",
    learningGoalsInfo: "Popüler öğrenme yollarından seçim yapın veya deneyiminizi özelleştirmek için kendi özel hedefinizi girin.",
    careerFieldsInfo: "İlgili ders önerileri almak için sektörünüzü veya ilgi alanınızı seçin.",
    courseTopicsInfo: "Trend konulara göz atın veya ustalaşmak istediğiniz belirli konuları arayın.",
    loadingSuggestions: "Öneriler yükleniyor...",
    selectAnOption: "Bir seçenek belirleyin",
    searchOrSelectAnOption: "Bir seçenek arayın veya seçin",
    // Control Panel çevirileri
    studentControlPanel: "Öğrenci Kontrol Paneli",
    mentorControlPanel: "Mentor Kontrol Paneli",
    manageYourLearningJourney: "Öğrenme yolculuğunuzu yönetin ve ilerlemenizi takip edin",
    trackAndGuideYourStudents: "Öğrencilerinizin öğrenme ilerlemesini takip edin ve rehberlik edin",
    student: "Öğrenci",
    mentor: "Mentor",
    overview: "Genel Bakış",
    learningPaths: "Öğrenme Yolları",
    progress: "İlerleme",
    assignments: "Ödevler",
    achievements: "Başarılar",
    students: "Öğrenciler",
    activities: "Aktiviteler",
    messaging: "Mesajlaşma",
    totalStudyHours: "Toplam Ders Saatleri",
    coursesCompleted: "Tamamlanan Dersler",
    currentStreak: "Mevcut Seri",
    averageGrade: "Ortalama Not",
    days: "gün",
    myLearningPaths: "Öğrenme Yollarım",
    createNewPath: "Yeni Yol Oluştur",
    noLearningPaths: "Henüz Öğrenme Yolu Yok",
    createFirstPath: "Kişiselleştirilmiş öğrenmeye başlamak için ilk öğrenme yolunuzu oluşturun.",
    createLearningPath: "Öğrenme Yolu Oluştur",
    viewDetails: "Detayları Görüntüle",
    delete: "Sil",
    learningPathDeleted: "Öğrenme Yolu Silindi",
    learningPathDeletedDesc: "Öğrenme yolunuz başarıyla silindi.",
    error: "Hata",
    learningPathDeleteError: "Öğrenme yolu silinemedi.",
    confirmDelete: "Bu öğrenme yolunu silmek istediğinizden emin misiniz?",
    weeklyProgress: "Haftalık İlerleme",
    yourStudyActivityOverTime: "Geçen hafta boyunca ders aktiviteniz",
    upcomingAssignments: "Yaklaşan Ödevler",
    assignmentsDueSoon: "Ödevleriniz ve teslim tarihleri",
    noUpcomingAssignments: "Yaklaşan ödev yok",
    myAchievements: "Başarılarım",
    recentAchievementsAndBadges: "Kazandığınız son başarılar ve rozetler",
    noAchievementsYet: "Henüz başarı yok. İlk rozetnizi kazanmak için öğrenmeye devam edin!",
    totalStudents: "Toplam Öğrenci",
    activeStudents: "Aktif Öğrenciler",
    weeklyStudyHours: "Haftalık Ders Saatleri",
    completionRate: "Tamamlama Oranı",
    studentsNeedingAttention: "Dikkat Gerektiren Öğrenciler",
    studentsWithLowGradesOrInactivity: "Düşük notlu veya son zamanlarda aktif olmayan öğrenciler",
    topPerformers: "En İyi Performans Gösterenler",
    studentsWithHighGrades: "Çalışmalarında başarılı olan öğrenciler",
    contact: "İletişim",
    allStudents: "Tüm Öğrenciler",
    completeOverviewOfAllStudents: "Tüm öğrencilerinizin ve ilerlemelerinin kapsamlı görünümü",
    courses: "Dersler",
    studyTime: "Ders Süresi",
    streak: "Seri",
    lastActivity: "Son Aktivite",
    actions: "İşlemler",
    view: "Görüntüle",
    recentActivities: "Son Aktiviteler",
    latestStudentActivitiesAndProgress: "En son öğrenci aktiviteleri ve ilerleme güncellemeleri",
    noRecentActivities: "Görüntülenecek son aktivite yok",
    sendMessage: "Öğrenciye Mesaj Gönder",
    communicateDirectlyWithYourStudents: "Öğrencilerinizle doğrudan iletişim kurun",
    selectStudent: "Öğrenci Seç",
    chooseStudent: "Bir öğrenci seçin...",
    messagingTo: "Şu kişiye mesaj gönderiliyor",
    message: "Mesaj",
    typeYourMessage: "Mesajınızı buraya yazın...",
    sending: "Gönderiliyor...",
    cancel: "İptal",
    messageSent: "Mesaj Gönderildi",
    messagesSentSuccessfully: "Mesajınız öğrenciye gönderildi.",
    failedToSendMessage: "Mesaj gönderilemedi. Lütfen tekrar deneyin."
  }
};

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<'en' | 'tr'>('en');

  const t = (key: string, fallback?: string) => {
    return translations[language][key as keyof typeof translations['en']] || fallback || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}