{
  studentId: string,
  date: string, // for which date the plan is (e.g., 'YYYY-MM-DD')
  subjects: {
    [subject]: {
      topics: array of strings, // topics to cover
      timeAllocated: number, // in minutes
      resources: array of strings, // links or resource names
    }
  },
  studyTips: string, // generated by OpenAI
  motivationalFeedback: string, // generated by OpenAI
  completed: boolean, // whether the plan was completed
  createdAt: timestamp
}