-- Enable Row Level Security (RLS) on all tables
-- Run this script in Neon SQL Editor to secure your database

-- Core User & Course Tables
ALTER TABLE users ENABLE ROW LEVEL SECURITY;
ALTER TABLE courses ENABLE ROW LEVEL SECURITY;
ALTER TABLE user_courses ENABLE ROW LEVEL SECURITY;
ALTER TABLE course_categories ENABLE ROW LEVEL SECURITY;
ALTER TABLE course_tags ENABLE ROW LEVEL SECURITY;

-- Assignments & Lessons
ALTER TABLE assignments ENABLE ROW LEVEL SECURITY;
ALTER TABLE user_assignments ENABLE ROW LEVEL SECURITY;
ALTER TABLE modules ENABLE ROW LEVEL SECURITY;
ALTER TABLE lessons ENABLE ROW LEVEL SECURITY;
ALTER TABLE user_lessons ENABLE ROW LEVEL SECURITY;

-- Challenges & Gamification
ALTER TABLE challenges ENABLE ROW LEVEL SECURITY;
ALTER TABLE user_challenges ENABLE ROW LEVEL SECURITY;
ALTER TABLE skill_challenges ENABLE ROW LEVEL SECURITY;
ALTER TABLE user_skill_challenge_attempts ENABLE ROW LEVEL SECURITY;
ALTER TABLE challenge_learning_paths ENABLE ROW LEVEL SECURITY;
ALTER TABLE challenge_path_steps ENABLE ROW LEVEL SECURITY;
ALTER TABLE user_challenge_streaks ENABLE ROW LEVEL SECURITY;

-- Achievements & Progress
ALTER TABLE achievements ENABLE ROW LEVEL SECURITY;
ALTER TABLE user_achievements ENABLE ROW LEVEL SECURITY;
ALTER TABLE user_levels ENABLE ROW LEVEL SECURITY;
ALTER TABLE user_progress ENABLE ROW LEVEL SECURITY;
ALTER TABLE user_progress_snapshots ENABLE ROW LEVEL SECURITY;
ALTER TABLE user_skill_progress ENABLE ROW LEVEL SECURITY;
ALTER TABLE user_skill_levels ENABLE ROW LEVEL SECURITY;

-- Learning Paths & Curriculums
ALTER TABLE learning_paths ENABLE ROW LEVEL SECURITY;
ALTER TABLE learning_path_steps ENABLE ROW LEVEL SECURITY;
ALTER TABLE curriculums ENABLE ROW LEVEL SECURITY;
ALTER TABLE user_curriculums ENABLE ROW LEVEL SECURITY;
ALTER TABLE course_curriculums ENABLE ROW LEVEL SECURITY;
ALTER TABLE curriculum_modules ENABLE ROW LEVEL SECURITY;
ALTER TABLE curriculum_checkpoints ENABLE ROW LEVEL SECURITY;
ALTER TABLE user_curriculum_tasks ENABLE ROW LEVEL SECURITY;
ALTER TABLE memory_enhanced_curricula ENABLE ROW LEVEL SECURITY;

-- Exams & Education Systems
ALTER TABLE exam_categories ENABLE ROW LEVEL SECURITY;
ALTER TABLE exam_schedules ENABLE ROW LEVEL SECURITY;
ALTER TABLE user_exam_reminders ENABLE ROW LEVEL SECURITY;
ALTER TABLE education_systems ENABLE ROW LEVEL SECURITY;
ALTER TABLE international_exam_categories ENABLE ROW LEVEL SECURITY;

-- Study Planning
ALTER TABLE study_plans ENABLE ROW LEVEL SECURITY;
ALTER TABLE study_sessions ENABLE ROW LEVEL SECURITY;
ALTER TABLE study_goals ENABLE ROW LEVEL SECURITY;
ALTER TABLE study_habits ENABLE ROW LEVEL SECURITY;
ALTER TABLE study_milestones ENABLE ROW LEVEL SECURITY;
ALTER TABLE study_progress ENABLE ROW LEVEL SECURITY;
ALTER TABLE study_programs ENABLE ROW LEVEL SECURITY;
ALTER TABLE study_schedules ENABLE ROW LEVEL SECURITY;
ALTER TABLE weekly_study_plans ENABLE ROW LEVEL SECURITY;
ALTER TABLE daily_study_goals ENABLE ROW LEVEL SECURITY;
ALTER TABLE daily_study_sessions ENABLE ROW LEVEL SECURITY;
ALTER TABLE daily_study_tasks ENABLE ROW LEVEL SECURITY;
ALTER TABLE daily_tasks ENABLE ROW LEVEL SECURITY;
ALTER TABLE study_plan_adjustments ENABLE ROW LEVEL SECURITY;
ALTER TABLE program_schedules ENABLE ROW LEVEL SECURITY;

-- AI & Recommendations
ALTER TABLE ai_profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE ai_suggestions ENABLE ROW LEVEL SECURITY;
ALTER TABLE ai_curriculum_generation_sessions ENABLE ROW LEVEL SECURITY;
ALTER TABLE ai_daily_plans ENABLE ROW LEVEL SECURITY;
ALTER TABLE ai_learning_data ENABLE ROW LEVEL SECURITY;
ALTER TABLE ai_recommendation_state ENABLE ROW LEVEL SECURITY;
ALTER TABLE ai_concept_logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE ai_review_logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE ai_study_tips_logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE ai_integration_log ENABLE ROW LEVEL SECURITY;
ALTER TABLE ai_modules ENABLE ROW LEVEL SECURITY;
ALTER TABLE ai_lessons ENABLE ROW LEVEL SECURITY;
ALTER TABLE course_suggestions ENABLE ROW LEVEL SECURITY;
ALTER TABLE course_recommendations ENABLE ROW LEVEL SECURITY;
ALTER TABLE goal_suggestions ENABLE ROW LEVEL SECURITY;
ALTER TABLE learning_recommendations ENABLE ROW LEVEL SECURITY;
ALTER TABLE personalized_recommendations ENABLE ROW LEVEL SECURITY;

-- User Data
ALTER TABLE user_interests ENABLE ROW LEVEL SECURITY;
ALTER TABLE user_goals ENABLE ROW LEVEL SECURITY;
ALTER TABLE user_activity_logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE user_usage_tracking ENABLE ROW LEVEL SECURITY;
ALTER TABLE enhanced_interaction_logs ENABLE ROW LEVEL SECURITY;

-- Social & Community
ALTER TABLE forum_posts ENABLE ROW LEVEL SECURITY;
ALTER TABLE forum_comments ENABLE ROW LEVEL SECURITY;
ALTER TABLE badges ENABLE ROW LEVEL SECURITY;
ALTER TABLE user_badges ENABLE ROW LEVEL SECURITY;
ALTER TABLE certificates ENABLE ROW LEVEL SECURITY;
ALTER TABLE leaderboards ENABLE ROW LEVEL SECURITY;
ALTER TABLE leaderboard_entries ENABLE ROW LEVEL SECURITY;
ALTER TABLE learning_milestones ENABLE ROW LEVEL SECURITY;
ALTER TABLE emoji_reactions ENABLE ROW LEVEL SECURITY;

-- TYT (Turkish Exam) Tables
ALTER TABLE tyt_student_profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE tyt_subjects ENABLE ROW LEVEL SECURITY;
ALTER TABLE tyt_topics ENABLE ROW LEVEL SECURITY;
ALTER TABLE tyt_trial_exams ENABLE ROW LEVEL SECURITY;
ALTER TABLE tyt_study_goals ENABLE ROW LEVEL SECURITY;
ALTER TABLE tyt_study_sessions ENABLE ROW LEVEL SECURITY;
ALTER TABLE tyt_study_streaks ENABLE ROW LEVEL SECURITY;
ALTER TABLE tyt_resources ENABLE ROW LEVEL SECURITY;

-- Other Tables
ALTER TABLE notifications ENABLE ROW LEVEL SECURITY;
ALTER TABLE reminders ENABLE ROW LEVEL SECURITY;
ALTER TABLE uploads ENABLE ROW LEVEL SECURITY;
ALTER TABLE essays ENABLE ROW LEVEL SECURITY;
ALTER TABLE course_analytics ENABLE ROW LEVEL SECURITY;
ALTER TABLE learning_analytics ENABLE ROW LEVEL SECURITY;
ALTER TABLE curriculum_design_parameters ENABLE ROW LEVEL SECURITY;
ALTER TABLE curriculum_design_process ENABLE ROW LEVEL SECURITY;
ALTER TABLE curriculum_feedback_loops ENABLE ROW LEVEL SECURITY;
ALTER TABLE curriculum_production_archives ENABLE ROW LEVEL SECURITY;
ALTER TABLE curriculum_success_metrics ENABLE ROW LEVEL SECURITY;
ALTER TABLE curriculum_skills ENABLE ROW LEVEL SECURITY;
ALTER TABLE course_integration_state ENABLE ROW LEVEL SECURITY;
ALTER TABLE module_dependency_graph ENABLE ROW LEVEL SECURITY;
ALTER TABLE module_integration_log ENABLE ROW LEVEL SECURITY;
ALTER TABLE user_trail_progress ENABLE ROW LEVEL SECURITY;
ALTER TABLE trail_nodes ENABLE ROW LEVEL SECURITY;
ALTER TABLE lesson_trails ENABLE ROW LEVEL SECURITY;
ALTER TABLE skill_assessments ENABLE ROW LEVEL SECURITY;
ALTER TABLE level_assessments ENABLE ROW LEVEL SECURITY;
ALTER TABLE assessment_questions ENABLE ROW LEVEL SECURITY;
ALTER TABLE mentors ENABLE ROW LEVEL SECURITY;
ALTER TABLE user_mentors ENABLE ROW LEVEL SECURITY;
ALTER TABLE user_program_progress ENABLE ROW LEVEL SECURITY;
ALTER TABLE user_topic_progress ENABLE ROW LEVEL SECURITY;
ALTER TABLE user_subscriptions ENABLE ROW LEVEL SECURITY;
ALTER TABLE subscription_plans ENABLE ROW LEVEL SECURITY;

-- Success message
DO $$
BEGIN
  RAISE NOTICE '✅ Row Level Security enabled on all tables!';
  RAISE NOTICE '⚠️  Remember to create RLS policies for proper access control.';
END $$;

